<?php
// NanoCM
// Copyright (C) 2017 - 2020 André Gewert <agewert@ubergeek.de>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

/* @var $this \Ubergeek\NanoCm\Module\CoreModule */

use Ubergeek\NanoCm\Article;

/* @var $medium \Ubergeek\NanoCm\Medium */
/* @var $format \Ubergeek\NanoCm\Media\ImageFormat */
/* @var $articleText string */

$medium = null;
$format = null;
if (!empty($this->article->medium_id) && ($format = $this->orm->getImageFormatByKey('banner')) !== null) {
    $medium = $this->orm->getMediumById($this->article->medium_id);
}

$articleText = (strlen($this->article->teaser) > 0)? $this->article->teaser : $this->article->content;
$articleText = $this->convertTextWithFullMarkup($articleText);
?>
<?php if ($this->article instanceof Article) : ?>
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-3"><a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>"><?php echo $this->htmlEncode($this->article->headline); ?></a></h1>

            <?php if ($format != null && $medium != null) : ?>
                <div class="figurecontainer">
                    <div class="imgcontainer">
                        <a class="imglink <?php echo $this->htmlEncode($format->key); ?>" href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>">
                            <img src="<?php echo $this->htmlConvUrl($medium->getImageUrl($format->key)); ?>"
                                 class="<?php echo $this->htmlEncode($format->key); ?>"
                                 title="<?php echo $this->htmlEncode($medium->title); ?>"
                                <?php if ($format->width > 0) echo "width=\"$format->width\""; ?>
                                <?php if ($format->height > 0) echo "height=\"$format->height\""; ?>>
                        </a>
                    </div>
                    <?php if (strlen($medium->attribution) > 0) : ?>
                        <div class="attribution"><?php echo $this->convertTextWithBasicMarkup($medium->attribution); ?></div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <?php echo $articleText; ?>
            <?php if (strlen($this->article->teaser) > 0) : ?>
                <p><a class="btn btn-primary btn-lg" href="<?php echo $this->htmlEncode($this->article->getArticleUrl()); ?>" role="button">Weiterlesen</a></p>
            <?php endif; ?>

            <div class="articlefooter">
                <p>Ver&ouml;ffentlicht von
                    <?php echo $this->htmlEncode($this->orm->convertUserIdToName($this->article->author_id, false)); ?>
                    am
                    <?php echo $this->htmlEncode($this->article->publishing_timestamp->format('d.m.Y')); ?>&nbsp;&bullet;
                    <a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>#comment">Kommentieren</a>&nbsp;&bullet;
                    <a href="<?php echo $this->htmlConvUrl($this->article->getEbookUrl()); ?>">ePub</a>&nbsp;&bullet;
                    <a href="<?php echo $this->htmlEncode(
                        \Ubergeek\NanoCm\Util::getTweetThisUrl(
                            $this->frontController->createAbsoluteSiteLink(
                                $this->article->getArticleUrl()
                            ),
                            $this->article->headline
                        )
                    ); ?>" target="_blank">Twittern</a>
                </p>
                <?php if (is_array($this->article->tags) && count($this->article->tags) > 0) : ?>
                    Schlagworte:
                    <ul class="taglist">
                        <?php foreach ($this->article->tags as $tag) : ?>
                            <li><a href="<?php echo $this->htmlConvUrl($this->article->getTagSearchUrl($tag)); ?>"><?php echo $this->htmlEncode($tag); ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
