<?php
/* @var $this \Ubergeek\NanoCm\Module\CoreModule */

use Ubergeek\NanoCm\Article;

/* @var $medium \Ubergeek\NanoCm\Medium */
/* @var $format \Ubergeek\NanoCm\Media\ImageFormat */
/* @var $articleText string */

$medium = null;
$format = null;
if (!empty($this->article->medium_id) && ($format = $this->orm->getImageFormatByKey('banner')) !== null) {
    $medium = $this->orm->getMediumById($this->article->medium_id);
}

$articleText = (strlen($this->article->teaser) > 0)? $this->article->teaser : $this->article->content;
$articleText = $this->convertTextWithFullMarkup($articleText);
?>
<?php if ($this->article instanceof Article) : ?>
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-3"><a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>"><?php echo $this->htmlEncode($this->article->headline); ?></a></h1>

            <?php if ($format != null && $medium != null) : ?>
                <div class="figurecontainer">
                    <div class="imgcontainer">
                        <a class="imglink <?php echo $this->htmlEncode($format->key); ?>" href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>">
                            <img src="<?php echo $this->htmlConvUrl($medium->getImageUrl($format->key)); ?>"
                                 class="<?php echo $this->htmlEncode($format->key); ?>"
                                 title="<?php echo $this->htmlEncode($medium->title); ?>"
                                <?php if ($format->width > 0) echo "width=\"$format->width\""; ?>
                                <?php if ($format->height > 0) echo "height=\"$format->height\""; ?>>
                        </a>
                    </div>
                    <?php if (strlen($medium->attribution) > 0) : ?>
                        <div class="attribution"><?php echo $this->convertTextWithBasicMarkup($medium->attribution); ?></div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <?php if (strlen($this->article->teaser) > 0) : ?>
                <div class="lead">
                    <?php echo $articleText; ?>
                </div>
                <p><a class="btn btn-outline-primary" href="<?php echo $this->htmlEncode($this->article->getArticleUrl()); ?>" role="button">Weiterlesen</a></p>
            <?php else : ?>
                <?php echo $articleText; ?>
            <?php endif; ?>

            <div class="articlefooter small">
                <p class="mb-0">Ver&ouml;ffentlicht von
                    <?php echo $this->htmlEncode($this->orm->convertUserIdToName($this->article->author_id, false)); ?>
                    am
                    <?php echo $this->htmlEncode($this->article->publishing_timestamp->format('d.m.Y')); ?>&nbsp;&bullet;
                    <a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>#comment">Kommentieren</a>&nbsp;&bullet;
                    <a href="<?php echo $this->htmlConvUrl($this->article->getEbookUrl()); ?>">ePub</a>&nbsp;&bullet;
                    <a href="<?php echo $this->htmlEncode(
                        \Ubergeek\NanoCm\Util::getTweetThisUrl(
                            $this->frontController->createAbsoluteSiteLink(
                                $this->article->getArticleUrl()
                            ),
                            $this->article->headline
                        )
                    ); ?>" target="_blank">Twittern</a>
                </p>
                <?php if (is_array($this->article->tags) && count($this->article->tags) > 0) : ?>
                    Schlagworte:
                    <?php foreach ($this->article->tags as $tag) : ?>
                        <a class="badge badge-secondary" href="<?php echo $this->htmlConvUrl($this->article->getTagSearchUrl($tag)); ?>"><?php echo $this->htmlEncode($tag); ?></a>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
