<?php
use Ubergeek\NanoCm\ContentConverter\Plugin\DownloadPluginOptions;
use Ubergeek\NanoCm\Module\TemplateRenderer\TemplateRenderer;
use Ubergeek\NanoCm\Util;

/* @var $this TemplateRenderer */
/* @var $options DownloadPluginOptions */
$medium = $options->medium;
?>
<div class="shadow download">
    <div class="icon">
        <p><a class="download" href="<?php echo $this->htmlConvUrl($this->getDownloadUrl($medium)); ?>">Download: <?php echo $this->htmlEncode($medium->title); ?></a><br>
            Dateigr&ouml;&szlig;e: <?php echo Util::sizeHumanReadable($medium->filesize); ?><br>
            &Auml;nderungsdatum: <?php echo $medium->modification_timestamp->format('Y-m-d H:i'); ?>
        </p>
        <?php if (!empty($medium->description)) : ?>
            <p class="description small"><?php echo $this->convertTextWithBasicMarkup($medium->description); ?></p>
        <?php endif; ?>
    </div>
</div>
