<?php

use Ubergeek\NanoCm\ContentConverter\Plugin\YoutubePluginOptions;
use Ubergeek\NanoCm\Module\TemplateRenderer\TemplateRenderer;

/* @var $this TemplateRenderer */
/* @var $options YoutubePluginOptions */
$options = $this->options;
$vid = $options->videoId;
$format = $options->previewImageFormat;
?>
<div class="video-preview" data-vid="<?php echo $this->htmlEncode($vid); ?>" style="max-width: 600px">
    <a href="https://www.youtube.com/watch?v=<?php echo $this->htmlEncode($vid); ?>" target="_blank">
        <img src="<?php echo $this->htmlConvUrl($this->getYoutubeThumbnailUrl($vid, 'ytthumb')); ?>"
            <?php if ($format !== null && $format->width > 0) echo "width=\"$format->width\""; ?>
            <?php if ($format !== null && $format->height > 0) echo "height=\"$format->height\""; ?>
             alt="Youtube" title="Youtube-Vorschau">
    </a>
</div>
