<?php
    /* @var $this \Ubergeek\NanoCm\Module\CoreModule */
?>
<div style="padding-top: 3.5em">
    <div class="container">
        <h1>Anmelden</h1>

        <?php if ($this->loginError) : ?>
            <div class="alert alert-warning" role="alert">
                <strong>Anmeldung fehlgeschlagen</strong><br>
                Die Anmeldung war nicht erfolgreich. Bitte &uuml;berpr&uuml;fen Sie Ihre Anmeldedaten.
            </div>
        <?php endif; ?>

        <form action="login.php">
            <input type="hidden" name="action" value="login" />
            
            <div class="form-group">
                <label for="input_username">Benutzername</label>
                <input class="form-control" id="input_username" name="username" type="text">
            </div>

            <div class="form-group">
                <label for="input_password">Passwort</label>
                <input class="form-control" id="input_password" name="password" type="password">
            </div>

            <button type="submit" class="btn btn-primary">Anmelden</button>
        </form>
    </div>
</div>
