<?php
    /* @var $mod \Ubergeek\NanoCm\Module\AbstractModule */
    $mod = $this;
    $mod->setTitle($mod->orm->getPageTitle() . ' - Anmelden');
?>
<div style="padding-top: 3.5em">
    <div class="container">
        <h1>Anmelden</h1>

        <form action="login.php">
            <input type="hidden" name="action" value="login" />
            
            <div class="form-group">
                <label for="input_username">Benutzername</label>
                <input class="form-control" id="input_username" name="username" type="text">
            </div>

            <div class="form-group">
                <label for="input_password">Passwort</label>
                <input class="form-control" id="input_password" name="password" type="password">
            </div>

            <button type="submit" class="btn btn-primary">Anmelden</button>
        </form>
    </div>
</div>
