<?php
/*
 * Die Startseite zeigt in der Standardkonfiguration die neuesten Artikel
 * Ob und wie eine Seitenleiste gefüllt wird, kann konfiguriert werden
 */

/* @var $this \Ubergeek\NanoCm\Module\AbstractModule */

/** @var \Ubergeek\NanoCm\Article[] $latestArticles */
$latestArticles = $this->orm->getLatestArticles();
?>

<?php if (count($latestArticles) >= 1) : ?>
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3"><a href="<?php echo $this->htmlEncode($latestArticles[0]->getArticleUrl()); ?>"><?php echo $this->htmlEncode($latestArticles[0]->headline); ?></a></h1>
            <?php if (strlen($latestArticles[0]->teaser) > 0) : ?>
                <?php echo $this->ncm->convertFormattedText($latestArticles[0]->teaser); ?>
            <?php endif; ?>
            <?php echo $this->ncm->convertFormattedText($latestArticles[0]->content); ?>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Weiterlesen &raquo;</a></p>
        </div>
    </div>

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
        </div>
    </div>
<?php else : ?>
    <?php // ??? ?>
<?php endif; ?>
