<?php
    /* @var $mod \Ubergeek\NanoCm\Module\AbstractModule */
    $mod = $this;
?>
<div style="padding-top: 3.5em">
    <div class="container">
        <h1>Fehler</h1>

        <p>Huch, es ist ein scherwiegender Fehler aufgetreten.<br>
            Bitte laden Sie die Seite neu. Falls der Fehler bestehen sollte,
            wenden Sie sich gerne an den Webseiten-Betreuer!</p>

        <?php if ($mod->exception !== null) : ?>
            <?php // TODO Art der Fehlerausgabe sollte konfigurierbar sein! ?>
            <pre><?php echo $mod->exception->getTraceAsString(); ?></pre>
            <?php //$mod->debug($mod->exception->getTraceAsString()); ?>
        <?php endif; ?>
    </div>
</div>
