<!DOCTYPE html>
<?php
    /* @var $fc Ubergeek\NanoCm\FrontController */
    $fc = $this;
?>
<html lange="de">
    <head>
        <meta charset="utf-8">        
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <base href="<?php echo $fc->ncm->relativeBaseUrl; ?>">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <title><?php echo $fc->htmlEncode($fc->getTitle()); ?></title>
        <style type="text/css">
            body {
                padding-top: 3.5rem;
            }
        </style>
    </head>
    <body>
        <?php echo $fc->includeUserTemplate('navigation-main.phtml'); ?>
        
        <?php echo $fc->getContent(); ?>
        
        <div class="container">
            <hr>
            <footer>
                <p><?php echo $fc->htmlEncode($fc->ncm->orm->getCopyrightNotice()); ?></p>
            </footer>
        </div>
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    </body>
</html>