<?php /* @var $this \Ubergeek\NanoCm\Module\CoreModule */ ?>

<div class="container">
    <h1>Anmelden</h1>

    <?php if ($this->loginError) : ?>
        <div class="alert alert-warning" role="alert">
            <strong>Anmeldung fehlgeschlagen</strong><br>
            Die Anmeldung war nicht erfolgreich. Bitte &uuml;berpr&uuml;fen Sie Ihre Anmeldedaten.
        </div>
    <?php endif; ?>

    <form action="<?php echo $this->htmlConvUrl('/login.php'); ?>" method="post">
        <input type="hidden" name="action" value="login" />

        <div class="form-group">
            <label for="input_username">Benutzername</label>
            <input class="form-control" id="input_username" name="username" type="text" autofocus="autofocus">
        </div>

        <div class="form-group">
            <label for="input_password">Passwort</label>
            <input class="form-control" id="input_password" name="password" type="password">
        </div>

        <p style="text-align: right">
            <button type="submit" class="button">Anmelden</button>
        </p>
    </form>
</div>
