<?php
/* @var $this Ubergeek\NanoCm\Module\CoreModule */
$medium = null;
$format = null;
$class = ($this->article->articleType instanceof \Ubergeek\NanoCm\Definition)? $this->article->articleType->value : '';

if (!empty($this->article->medium_id)) {
    if (($format = $this->orm->getImageFormatByKey('banner')) !== null) {
        $medium = $this->orm->getMediumById($this->article->medium_id);
    }
}
?>

<div class="container">
    <article class="<?php echo $class; ?>">
        <h1><?php echo $this->htmlEncode($this->article->headline); ?></h1>

        <?php if ($format != null && $medium != null) : ?>
            <div class="imgcontainer">
                <img src="<?php echo $this->htmlConvUrl($medium->getImageUrl($format->key)); ?>"
                     class="<?php echo $this->htmlEncode($format->key); ?>"
                     title="<?php echo $this->htmlEncode($medium->title); ?>"
                    <?php if ($format->width > 0) echo "width=\"$format->width\""; ?>
                    <?php if ($format->height > 0) echo "height=\"$format->height\""; ?>>
                <?php if (strlen($medium->attribution) > 0) : ?>
                    <div class="attribution"><?php echo $this->ncm->convertCommentText($medium->attribution); ?></div>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <?php echo $this->ncm->convertFormattedText($this->article->content); ?>

        <?php $this->includeUserTemplate('blocks/media-image.phtml'); ?>

        <div class="articlefooter">
            <p>Ver&ouml;ffentlicht von
                <?php echo $this->htmlEncode($this->orm->convertUserIdToName($this->article->author_id, false)); ?>
                am
                <?php echo $this->htmlEncode($this->article->publishing_timestamp->format('d.m.Y')); ?>
                &bullet;
                <a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>#comments">Kommentieren</a>
                &bullet;
                <a href="<?php echo $this->htmlEncode(
                    \Ubergeek\NanoCm\Util::getTweetThisUrl(
                        $this->frontController->createAbsoluteSiteLink(
                            $this->article->getArticleUrl()
                        ),
                        $this->article->headline
                    )
                ); ?>" target="_blank">Twittern</a>
            </p>
            <?php if (is_array($this->article->tags) && count($this->article->tags) > 0) : ?>
                Schlagworte:
                <ul class="taglist">
                    <?php foreach ($this->article->tags as $tag) : ?>
                        <li><a href="<?php echo $this->htmlConvUrl($this->article->getTagSearchUrl($tag)); ?>"><?php echo $this->htmlEncode($tag); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    </article>

    <?php if ($this->commentsEnabled) : ?>
        <?php if (is_array($this->comments) && count($this->comments) > 0) : ?>
            <h2>Kommentare</h2>

            <ol class="comments">
                <?php $i = 0; ?>
                <?php foreach ($this->comments as $comment) : ?>
                    <?php $i++; ?>
                    <li class="<?php echo ($i %2 == 0)? 'even' : 'odd'; ?>">
                        <h3><a name="comment-<?php echo intval($comment->id); ?>"></a><?php echo $i; ?>.</h3>
                        <div class="entry">
                            <?php if ($comment->use_gravatar) : ?>
                                <div class="userimg"><img src="<?php echo $this->htmlEncode(\Ubergeek\NanoCm\Util::getGravatarUserImageUrl($comment->email)); ?>" alt=""></div>
                            <?php endif; ?>
                            <h4><?php echo $this->htmlEncode($comment->username . ': ' . $comment->headline); ?></h4>

                            <p><?php echo $this->ncm->convertCommentText($this->htmlEncode($comment->content)); ?></p>

                            <div class="details">
                                <p>Geschrieben am <?php echo $comment->creation_timestamp->format('d.m.y, H:i'); ?></p>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        <?php endif; ?>

        <?php if ($this->article->enable_comments) : ?>
            <div class="nonprint">
                <h2><a name="comment"></a>Kommentar hinterlassen</h2>

                <?php echo $this->includeUserTemplate('blocks/usermessages.phtml'); ?>

                <form action="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>#comment" method="post" class="stdform">
                    <input type="hidden" name="cpsid" value="<?php echo $this->htmlEncode($this->captcha->captchaId); ?>">

                    <div class="form-group">
                        <label for="input_n">Dein Name</label>
                        <input type="text" class="text form-control" id="input_n" name="_n" required value="<?php echo $this->htmlEncode($this->commentName); ?>" maxlength="45">
                    </div>
                    <div class="form-group">
                        <label for="input_e">E-Mail (wird nicht angezeigt)</label>
                        <input type="email" class="text form-control" id="input_e" name="_e" required value="<?php echo $this->htmlEncode($this->commentMail); ?>" maxlength="128">
                    </div>
                    <div class="form-group">
                        <input type="checkbox" id="_g" name="_g" value="1"<?php if ($this->commentUseGravatar == '1') echo ' checked="checked"'; ?>>
                        <label for="_g">Ich m&ouml;chte, dass mein Gravatar angezeigt wird</label>
                    </div>
                    <div class="form-group">
                        <label for="input_h">&Uuml;berschrift (optional)</label>
                        <input type="text" class="text form-control" id="input_h" name="_h" value="<?php echo $this->htmlEncode($this->commentHeadline); ?>" maxlength="100">
                    </div>
                    <div class="form-group">
                        <textarea wrap="soft" id="input_t" name="_t" style="height: 10em" required class="form-control"><?php echo $this->htmlEncode($this->commentText); ?></textarea>
                    </div>

                    <div class="form-group">
                        <label for="input_sc">Sicherheitsfrage:
                            <?php echo intval($this->captcha->valueA); ?>&nbsp;<?php echo $this->captcha->operator; ?>&nbsp;<?php echo intval($this->captcha->valueB); ?>
                            ergibt
                        </label>
                        <input type="text" class="text form-control" id="input_sc" name="sc" value="" required autocomplete="off">
                    </div>

                    <div class="form-group" style="text-align: right">
                        <input type="hidden" name="ac" value="s" />
                        <input type="submit" class="button" value="Kommentieren">
                    </div>
                </form>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>
