<?php
/* @var $this \Ubergeek\NanoCm\Module\CoreModule */
/* @var $latestArticles \Ubergeek\NanoCm\Article[] */
$latestArticles = $this->orm->getLatestArticles(8);
//$fullArticles = $this->orm->getLatestArticlesByArticleType('mini', true, true, 8);
//$miniArticles = $this->orm->getLatestArticlesByArticleType('mini', true, false, 7);
//$this->log->debug($fullArticles);
//$this->log->debug($miniArticles);
?>

<div class="container">
    <?php if (count($latestArticles) > 0) : ?>
        <?php
            $this->article = array_shift($latestArticles);
            $this->includeUserTemplate('blocks/article-teaser-big.phtml');
        ?>
        <?php while (($this->article = array_shift($latestArticles)) !== null) : ?>
            <?php $this->includeUserTemplate('blocks/article-teaser-normal.phtml'); ?>
        <?php endwhile; ?>
    <?php else : ?>
        <div class="spacing">
            <h1>Noch keine Inhalte vorhanden</h1>
            <p>Leider gibt es hier noch nichts zu sehen!</p>
        </div>
    <?php endif; ?>
</div>
