<?php
/* @var $this Ubergeek\NanoCm\Module\CoreModule */

$medium = null;
$format = null;

if (!empty($this->article->medium_id)) {
    if (($format = $this->orm->getImageFormatByKey('banner')) !== null) {
        $medium = $this->orm->getMediumById($this->article->medium_id);
    }
}
?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n"; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de">
    <head>
        <title>Testinhalt</title>
        <link rel="stylesheet" href="<?php echo $this->htmlConvUrl('/tpl/ubergeek/css/epub.css'); ?>" type="text/css" />
    </head>
    <body>
        <div class="article">
            <h1><?php echo $this->htmlEncode($this->article->headline); ?></h1>

            <?php if ($format != null && $medium != null) : ?>
                <div class="figurecontainer">
                    <div class="imgcontainer">
                        <img src="<?php echo $this->htmlConvUrl($medium->getImageUrl($format->key)); ?>"
                             class="<?php echo $this->htmlEncode($format->key); ?>"
                             title="<?php echo $this->htmlEncode($medium->title); ?>"
                            <?php if ($format->width > 0) echo "width=\"$format->width\""; ?>
                            <?php if ($format->height > 0) echo "height=\"$format->height\""; ?> />
                    </div>
                    <?php if (strlen($medium->attribution) > 0) : ?>
                        <div class="attribution"><?php echo $this->convertTextWithBasicMarkup($medium->attribution); ?></div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <?php if (strlen($this->article->teaser) > 0) : ?>
                <div class="lead">
                    <?php echo $this->convertTextWithFullMarkup($this->article->teaser); ?>
                </div>
            <?php endif; ?>

            <?php echo $this->convertTextWithFullMarkup($this->article->content); ?>

            <div class="articlefooter">
                <p>Veröffentlicht von
                    <?php echo $this->htmlEncode($this->orm->convertUserIdToName($this->article->author_id, false)); ?>
                    am
                    <?php echo $this->htmlEncode($this->article->publishing_timestamp->format('d.m.Y')); ?>
                </p>
                <?php if (is_array($this->article->tags) && count($this->article->tags) > 0) : ?>
                    Schlagworte:
                    <ul class="taglist">
                        <?php foreach ($this->article->tags as $tag) : ?>
                            <li><a href="<?php echo $this->htmlConvUrl($this->article->getTagSearchUrl($tag)); ?>"><?php echo $this->htmlEncode($tag); ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
    </body>
</html>