<?php /* @var $this \Ubergeek\NanoCm\Module\AbstractModule */ ?>
<div class="container spacing">
    <h1>Fehler</h1>

    <p>Huch, es ist ein scherwiegender Fehler aufgetreten.<br>
        Bitte laden Sie die Seite neu. Falls der Fehler bestehen sollte,
        wenden Sie sich gerne an den Webseiten-Betreuer!</p>

    <?php if ($this->exception !== null && $this->ncm->showExceptions) : ?>
        <?php $ex = $this->exception; ?>

        <?php do { ?>
            <p><b><?php echo $this->htmlEncode($ex->getMessage()); ?></b></p>
            <?php echo nl2br($ex->getTraceAsString()); ?>
            <?php $this->debug($ex->getTraceAsString()); ?>
        <?php } while (($ex = $ex->getPrevious()) != null); ?>

    <?php endif; ?>
</div>
