<?php /* @var $this \Ubergeek\NanoCm\Module\AbstractModule */ ?>
<div class="container spacing">
    <h1>Fehler</h1>

    <p>Huch, es ist ein scherwiegender Fehler aufgetreten.<br>
        Bitte laden Sie die Seite neu. Falls der Fehler bestehen sollte,
        wenden Sie sich gerne an den Webseiten-Betreuer!</p>

    <?php if ($this->exception !== null) : ?>
        <?php // TODO Art der Fehlerausgabe sollte konfigurierbar sein! ?>
        <p><b><?php echo $this->htmlEncode($this->exception->getMessage()); ?></b></p>
        <?php echo nl2br($this->exception->getTraceAsString()); ?>
        <?php $this->debug($this->exception->getTrace()); ?>
    <?php endif; ?>
</div>
