<?php /* @var $this \Ubergeek\NanoCm\Module\AbstractModule */ ?>
<div class="container">
    <h1>Anmeldung fehlgeschlagen</h1>

    <p>F&uuml;r den Zugriff auf die angeforderte Ressource sind besondere
        Berechtigungen erforderlich.<br>
        Bitte melden Sie sich mit einem
        entsprechend authorisierten Benutzerkonto am System an.</p>

    <p><a href="/login.php">Zur Anmeldung</a></p>
</div>
