<?php /* @var $this \Ubergeek\NanoCm\Module\AbstractModule */ ?>
<div class="frame bg-nav-dark">
    <div class="container">
        <nav class="mainnavigation">
            <ul>
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="/weblog/archiv/">Weblog-Archiv</a>
                </li>
                <li>
                    <a href="/meta/kontakt.html">Kontakt</a>
                </li>
                <li>
                    <a href="/meta/datenschutz.html">Datenschutz</a>
                </li>
                <?php if ($this->ncm->isUserLoggedIn()) : ?>
                    <li>
                        <a href="/admin/index.php">Verwaltung</a>
                    </li>
                <?php endif; ?>
            </ul>
        </nav>
    </div>
</div>