<?php
/* @var $this \Ubergeek\NanoCm\Module\AbstractModule */
$items = $this->orm->getReleasedUserListItemsByListKey('mainnav');
if (count($items) == 0) {
    $item = new \Ubergeek\NanoCm\UserListItem();
    $item->title = 'Home';
    $item->content = '/';
    array_push($items, $item);
}
?>
<nav class="mainnavigation nonprint">
    <div class="container">
        <ul>
            <?php foreach ($items as $listItem) : ?>
                <li>
                    <a href="<?php echo $this->htmlConvUrl($listItem->content); ?>"><?php echo $this->htmlEncode($listItem->title); ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</nav>