<!DOCTYPE html>
<?php /* @var $this \Ubergeek\NanoCm\Module\AbstractModule */ ?>
<html lang="<?php echo $this->htmlEncode($this->ncm->lang); ?>">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="theme-color" content="#02111b">
        <meta name="robots" content="INDEX,FOLLOW" />
        <meta name="revisit-after" content="2 days" />
        <meta name="generator" content="<?php echo $this->htmlEncode($this->ncm->versionInfo->generator); ?>" />
        <meta http-equiv="content-Type" content="text/html; utf-8" />
        <meta http-equiv="Pragma" content="cache" />
        <meta http-equiv="content-Language" content="<?php echo $this->htmlEncode($this->ncm->lang); ?>" />

        <title><?php echo $this->htmlEncode($this->getTitle()); ?></title>

        <link rel="stylesheet" href="<?php echo $this->htmlConvUrl('/tpl/ubergeek/css/frame.css'); ?>" />
        <link rel="stylesheet" href="<?php echo $this->htmlConvUrl('/tpl/ubergeek/css/content.css'); ?>" />
        <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->htmlConvUrl('/tpl/ubergeek/img/favicon-32x32.png'); ?>">
        <link href="<?php echo $this->htmlConvUrl('/tpl/ubergeek/ext/lightbox/css/lightbox.css'); ?>" rel="stylesheet">
        <link href="<?php echo $this->htmlConvUrl('/tpl/ubergeek/ext/highlight/styles/default.css'); ?>" rel="stylesheet">

        <script src="<?php echo $this->htmlConvUrl('/ncm/js/jquery-3.5.1.min.js'); ?>"></script>
        <script src="<?php echo $this->htmlConvUrl('/tpl/ubergeek/ext/lightbox/js/lightbox.js'); ?>"></script>
        <script src="<?php echo $this->htmlConvUrl('/tpl/ubergeek/ext/highlight/highlight.pack.js'); ?>"></script>
        <script src="<?php echo $this->htmlConvUrl('/ncm/js/ncm-public.js'); ?>"></script>
        <script type="text/javascript">
            ncmPublic = new NcmPublic('<?php echo $this->convUrl('/'); ?>');
        </script>
        <script src="<?php echo $this->htmlConvUrl('/tpl/ubergeek/script/ubergeek.js'); ?>"></script>

        <link rel="alternate" type="application/atom+xml" title="Neueste Artikel" href="<?php echo $this->htmlConvUrl('/weblog/feed/'); ?>" />
        <link rel="alternate" type="application/atom+xml" title="Neueste Kommentare" href="<?php echo $this->htmlConvUrl('/weblog/feed/comments/'); ?>" />
    </head>
    <body>
        <header>
            <div class="container brand">
                <a class="nonprint" href="<?php echo $this->htmlConvUrl('/'); ?>"><img src="<?php echo $this->htmlConvUrl('tpl/ubergeek/img/ubergeek-logo.png'); ?>" width="346" height="38" alt="<?php echo $this->htmlEncode($this->getSiteTitle()); ?>" /></a>
                <img class="printonly" src="<?php echo $this->htmlConvUrl('tpl/ubergeek/img/ubergeek-logo-black.png'); ?>" width="346" height="38" alt="<?php echo $this->htmlEncode($this->getSiteTitle()); ?>" />
                <?php $this->includeUserTemplate('navigation-meta.phtml'); ?>
            </div>
        </header>

        <?php $this->includeUserTemplate('navigation-main.phtml'); ?>

        <?php if (!$this->ncm->hasCurrentUserAcceptedPrivacyPolicy()) : ?>
            <?php $this->includeUserTemplate('blocks/privacy.phtml') ?>
        <?php endif; ?>

        <main>
            <?php echo $this->getContent(); ?>
        </main>

        <footer>
            <div class="container">
                <div class="column-4 nonprint" style="padding-right: 0.25em">
                    <h1>Neueste Artikel</h1>
                    <?php if (count(($articles = $this->orm->getLatestArticles(6))) > 0) : ?>
                        <ul class="nobullets">
                            <?php foreach ($articles as $article) : ?>
                                <li>
                                    <?php echo $this->htmlEncode($article->publishing_timestamp->format('d.m.')); ?>
                                    <a href="<?php echo $this->htmlConvUrl($article->getArticleUrl()); ?>"><?php echo $this->htmlEncode($article->headline); ?></a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php else : ?>
                        <p>Noch keine Artikel</p>
                    <?php endif; ?>
                </div>
                <div class="column-4 nonprint" style="padding: 0 0.25em">
                    <h1>Kommentare</h1>
                    <?php if (count(($comments = $this->orm->getLatestComments())) > 0) : ?>
                        <ul class="nobullets">
                            <?php foreach ($comments as $comment) : ?>
                                <?php $article = $this->orm->getArticleById($comment->article_id); ?>
                                <li>
                                    <?php echo $comment->creation_timestamp->format('d.m.'); ?>
                                    <a href="<?php echo $this->convUrl($article->getCommentUrl($comment)); ?>">
                                        <?php echo $this->htmlEncode($comment->username); ?>
                                        zu
                                        <?php echo $this->htmlEncode($this->orm->getArticleHeadlineById($comment->article_id)); ?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php else : ?>
                        <p>Noch keine Kommentare</p>
                    <?php endif; ?>
                </div>
                <div class="column-4 nonprint" style="padding-left: 0.25em">
                    <h1>Woanders</h1>
                    <ul class="nobullets">
                        <li><a class="extern" href="https://github.com/andregewert">Github</a></li>
                        <li><a class="extern" href="https://mstdn.social/@agewert">Mastodon</a></li>
                        <li><a class="extern" href="https://instagram.com/agewert">Instagram</a></li>
                    </ul>
                </div>
                <div style="clear: both; text-align: center; padding-top: 3rem">
                    <p><?php echo $this->htmlEncode($this->ncm->orm->getCopyrightNotice()); ?>&nbsp;&middot;
                        <?php if ($this->ncm->isUserLoggedIn()) : ?>
                            <a href="<?php echo $this->htmlConvUrl('/admin/index.php'); ?>">Verwaltung</a>
                            &middot;&nbsp;<a href="<?php echo $this->htmlConvUrl('/logout.php'); ?>">Abmelden</a>
                        <?php else : ?>
                            <a href="<?php echo $this->htmlConvUrl('/login.php'); ?>">Anmelden</a>
                        <?php endif; ?>
                        <br>
                        <a href="<?php echo $this->htmlConvUrl('/weblog/feed/'); ?>" class="feed" title="Feed: Neueste Artikel" rel="alternate" type="application/atom+xml">Artikel-Feed</a>&nbsp;&middot;
                        <a href="<?php echo $this->htmlConvUrl('/weblog/feed/comments/'); ?>" class="feed" title="Feed: Neueste Kommentare" rel="alternate" type="application/atom+xml">Kommentar-Feed</a>
                    </p>
                </div>
            </div>
        </footer>
        <script>
            $(function() {
                initUbergeek('<?php echo $this->htmlConvUrl('/tpl/ubergeek'); ?>');
            });
        </script>
    </body>
</html>