<!DOCTYPE html>
<?php /* @var $this \Ubergeek\NanoCm\Module\AbstractModule */ ?>
<html lang="de">
    <head>
        <meta charset="utf-8">        
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title><?php echo $this->htmlEncode($this->getTitle()); ?></title>
        <link rel="stylesheet" href="<?php echo $this->htmlConvUrl('/tpl/ubergeek/css/default.css'); ?>" />
        <link href="https://fonts.googleapis.com/css?family=Oswald|Fira+Sans|Anonymous+Pro|Barlow" rel="stylesheet">
        <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->htmlConvUrl('/tpl/ubergeek/img/favicon-32x32.png'); ?>">
        <meta name="theme-color" content="#000000">
    </head>
    <body>
        <div class="frame bg-header-light">
            <div class="container brand">
                <a href="<?php echo $this->htmlConvUrl('/'); ?>"><img src="<?php echo $this->htmlConvUrl('tpl/ubergeek/img/ubergeek-logo.png'); ?>" width="368" height="38" alt="<?php echo $this->htmlEncode($this->getSiteTitle()); ?>" /></a>
                <?php echo $this->includeUserTemplate('navigation-meta.phtml'); ?>
            </div>
        </div>
        <?php echo $this->includeUserTemplate('navigation-main.phtml'); ?>
        <div class="frame bg-frame">
            <div class="container" style="height: 1.2rem"></div>
            <?php echo $this->getContent(); ?>
            <div class="container" style="height: 100px"></div>
        </div>
        <div class="frame bg-header-light">
            <div class="container">
                <footer class="clearfix">
                    <div class="spacing column-4">
                        <h1>Neueste Artikel</h1>
                        <?php if (count(($articles = $this->orm->getLatestArticles(6))) > 0) : ?>
                            <ul class="nobullets">
                                <?php foreach ($articles as $article) : ?>
                                    <li>
                                        <?php echo $this->htmlEncode($article->publishing_timestamp->format('d.m.')); ?>
                                        <a href="<?php echo $this->htmlConvUrl($article->getArticleUrl()); ?>"><?php echo $this->htmlEncode($article->headline); ?></a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php else : ?>
                            <p>Noch keine Artikel</p>
                        <?php endif; ?>
                    </div>
                    <div class="spacing column-4">
                        <h1>Kommentare</h1>
                        <?php if (count(($comments = $this->orm->getLatestComments())) > 0) : ?>
                            <ul class="nobullets">
                                <?php foreach ($comments as $comment) : ?>
                                    <li>
                                        <?php echo $comment->creation_timestamp->format('d.m.'); ?>
                                        <a href="javascript:void(0)">
                                            <?php echo $this->htmlEncode($comment->username); ?>
                                            zu
                                            <?php echo $this->htmlEncode($this->orm->getArticleHeadlineById($comment->article_id)); ?>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php else : ?>
                            <p>Noch keine Kommentare</p>
                        <?php endif; ?>
                    </div>
                    <div class="spacing column-4">
                        <h1>Soziale Medien</h1>
                        <ul class="nobullets">
                            <li><a class="extern" href="http://instagram.com/agewert">Instagram</a></li>
                            <li><a class="extern" href="https://www.twitter.com/agewert">Twitter</a></li>
                            <li><a class="extern" href="https://www.facebook.com/andre.gewert">Facebook</a></li>
                        </ul>
                    </div>
                    <div style="clear: both; text-align: center; padding-top: 3rem" class="spacing">
                        <p><?php echo $this->htmlEncode($this->ncm->orm->getCopyrightNotice()); ?>&nbsp;&bullet;
                            <?php if ($this->ncm->isUserLoggedIn()) : ?>
                                <a href="<?php echo $this->htmlConvUrl('/admin/index.php'); ?>">Verwaltung</a>
                                &bullet;&nbsp;<a href="<?php echo $this->htmlConvUrl('/logout.php'); ?>">Abmelden</a>
                            <?php else : ?>
                                <a href="<?php echo $this->htmlConvUrl('/login.php'); ?>">Anmelden</a>
                            <?php endif; ?>
                        </p>
                    </div>
                </footer>
            </div>
        </div>
        <script src="<?php echo $this->htmlConvUrl('/ncm/js/jquery-3.3.1.min.js'); ?>"></script>
    </body>
</html>