<?php
/* @var $this Ubergeek\NanoCm\Module\CoreModule */
$lastYear = null;
$lastMonth = null;
$first = true;
$fmt = datefmt_create(
    $this->ncm->lang,
    IntlDateFormatter::FULL,
    IntlDateFormatter::FULL,
    'Europe/Berlin',
    IntlDateFormatter::GREGORIAN,
    'MMMM Y'
);
?>
<div class="container mt-4">
    <h1>Suche nach Schlagworten: <?php echo $this->htmlEncode(join(', ', $this->searchTags)); ?></h1>

    <p>Feed mit Artikel zu dieser Suche: <a href="<?php echo $this->htmlConvUrl('/weblog/feed/tags/' . join(', ', $this->searchTags)); ?>">Atom</a></p>

    <?php if (is_array($this->articles) && count($this->articles) > 0) : ?>
        <?php foreach ($this->articles as $article) : ?>
            <?php $pubDate = ($article->publishing_timestamp == null)? $article->start_timestamp : $article->publishing_timestamp; ?>
            <?php if ($pubDate->format('Y') != $lastYear || $pubDate->format('m') != $lastMonth) : ?>
                <?php if (!$first) : ?>
                    </ul>
                <?php endif; ?>
                <h2><?php echo $this->htmlEncode(datefmt_format($fmt, $pubDate->getTimestamp())); ?></h2>
                <ul class="nobullets">
            <?php endif; ?>
            <li>
                <?php echo $article->publishing_timestamp->format('d.m.Y'); ?>
                <a href="<?php echo $this->htmlConvUrl($article->getArticleUrl()); ?>"><?php echo $this->htmlEncode($article->headline); ?></a></h2>
            </li>
            <?php
                $lastMonth = $pubDate->format('m');
                $lastYear = $pubDate->format('Y');
                $first = false;
            ?>
        <?php endforeach; ?>
    <?php else : ?>
        <p>&mdash;&nbsp;Keine Artikel gefunden&nbsp;&mdash;</p>
    <?php endif; ?>
</div>
