<?php
/* @var $this \Ubergeek\NanoCm\Module\CoreModule */
/* @var $latestArticles \Ubergeek\NanoCm\Article[] */
$latestArticles = $this->orm->getLatestArticles(8);
?>

<?php if (count($latestArticles) >= 1) : ?>

    <?php
        $this->article = array_shift($latestArticles);
        $this->includeUserTemplate('blocks/article-teaser-big.phtml');
    ?>
    <?php while (($this->article = array_shift($latestArticles)) !== null) : ?>
        <?php $this->includeUserTemplate('blocks/article-teaser-normal.phtml'); ?>
    <?php endwhile; ?>
<?php else : ?>
    <div style="padding-top: 3.5em">
        <div class="container">
            <h1>Noch keine Inhalte vorhanden</h1>
            <p>Leider gibt es hier noch nichts zu sehen!</p>
        </div>
    </div>
<?php endif; ?>
