<?php /* @var $this Ubergeek\NanoCm\Module\CoreModule */ ?>
<?php echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n"; ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de">
    <head>
        <title><?php echo $this->htmlEncode($this->ebook->coverTitle); ?></title>
        <style type="text/css" title="override_css">
            @page {padding: 0pt; margin:0pt}
            body { text-align: center; padding:0pt; margin: 0pt; }
        </style>
    </head>
    <body>
        <div class="cover-img">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100%" height="100%" viewBox="0 0 565 800">
                <image width="565" height="800" xlink:href="<?php echo $this->htmlConvTplUrl('/img/EBookCover.jpeg'); ?>" />
                <text x="12" y="250" style="font-size:38pt; font-family:Oswald"><?php echo $this->htmlEncode($this->ebook->title); ?></text>
            </svg>
        </div>
    </body>
</html>