<?php
/* @var $this \Ubergeek\NanoCm\Module\AbstractModule */
$items = $this->orm->getReleasedUserListItemsByListKey('mainnav');
if (count($items) == 0) {
    $item = new \Ubergeek\NanoCm\UserListItem();
    $item->title = 'Home';
    $item->content = '/';
    array_push($items, $item);
}
?>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/"><?php echo $this->htmlEncode($this->getSiteTitle()); ?></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <?php foreach ($items as $listItem) : ?>
                <li class="nav-item active">
                    <a class="nav-link" href="<?php echo $this->htmlConvUrl($listItem->content); ?>"><?php echo $this->htmlEncode($listItem->title); ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</nav>