<?php
/* @var $this \Ubergeek\NanoCm\Module\AbstractModule */

use Ubergeek\NanoCm\UserListItem;

$items = $this->orm->getReleasedUserListItemsByListKey('mainnav');
if (count($items) == 0) {
    $item = new UserListItem();
    $item->title = 'Home';
    $item->content = '/';
    array_push($items, $item);
}

$itemsMeta = $this->orm->getReleasedUserListItemsByListKey('metanav');
?>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="<?php echo $this->htmlConvUrl('/'); ?>"><?php echo $this->htmlEncode($this->getSiteTitle()); ?></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
        <?php if (count($items) > 0) : ?>
            <ul class="navbar-nav mr-auto">
                <?php foreach ($items as $listItem) : ?>
                    <li class="nav-item active">
                        <a class="nav-link" href="<?php echo $this->htmlConvUrl($listItem->content); ?>"><?php echo $this->htmlEncode($listItem->title); ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <?php if (count($itemsMeta) > 0) : ?>
            <ul class="navbar-nav ml-auto">
                <?php foreach ($itemsMeta as $listItem) : ?>
                    <li class="nav-item"><a href="<?php echo $this->htmlConvUrl($listItem->content); ?>"><?php echo $this->htmlEncode($listItem->title); ?></a></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</nav>
