<!DOCTYPE html>
<?php /* @var $this \Ubergeek\NanoCm\Module\AbstractModule */ ?>
<html lang="<?php echo $this->htmlEncode($this->ncm->lang); ?>">
    <head>
        <meta charset="utf-8">        
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="robots" content="INDEX,FOLLOW" />
        <meta name="revisit-after" content="2 days" />
        <meta name="generator" content="<?php echo $this->htmlEncode($this->ncm->versionInfo->generator); ?>" />
        <meta http-equiv="content-Type" content="text/html; utf-8" />
        <meta http-equiv="Pragma" content="cache" />
        <meta http-equiv="content-Language" content="<?php echo $this->htmlEncode($this->ncm->lang); ?>" />

        <title><?php echo $this->htmlEncode($this->getTitle()); ?></title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="<?php echo $this->htmlConvTplUrl('/css/content.css'); ?>" />
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
        <script src="<?php echo $this->htmlConvUrl('/ncm/js/ncm-public.js'); ?>"></script>
        <script type="text/javascript">
            ncmPublic = new NcmPublic('<?php echo $this->convUrl('/'); ?>');
        </script>
    </head>
    <body>
        <?php echo $this->includeUserTemplate('navigation-main.phtml'); ?>

        <?php if (!$this->ncm->hasCurrentUserAcceptedPrivacyPolicy()) : ?>
            <?php $this->includeUserTemplate('blocks/privacy.phtml') ?>
        <?php endif; ?>
        
        <?php echo $this->getContent(); ?>

        <div class="mt-4 mb-4">&nbsp;</div>
        <div class="container mt-4">
            <hr>
            <footer>
                <p><?php echo $this->htmlEncode($this->ncm->orm->getCopyrightNotice()); ?>&nbsp;&middot;
                    <?php if ($this->ncm->isUserLoggedIn()) : ?>
                        <a href="<?php echo $this->htmlConvUrl('/admin/index.php'); ?>">Verwaltung</a>
                        &middot;&nbsp;<a href="<?php echo $this->htmlConvUrl('/logout.php'); ?>">Abmelden</a>
                    <?php else : ?>
                        <a href="<?php echo $this->htmlConvUrl('/login.php'); ?>">Anmelden</a>
                    <?php endif; ?>
                    &middot;
                    <a href="<?php echo $this->htmlConvUrl('/weblog/feed/'); ?>" class="feed" title="Feed: Neueste Artikel" rel="alternate" type="application/atom+xml">Artikel-Feed</a>&nbsp;&middot;
                    <a href="<?php echo $this->htmlConvUrl('/weblog/feed/comments/'); ?>" class="feed" title="Feed: Neueste Kommentare" rel="alternate" type="application/atom+xml">Kommentar-Feed</a>
                </p>
            </footer>
        </div>
    </body>
</html>