<?php
/* @var $this \Ubergeek\NanoCm\Module\CoreModule */
/* @var $medium \Ubergeek\NanoCm\Medium */
/* @var $format \Ubergeek\NanoCm\Media\ImageFormat */
/* @var $articleText string */

$medium = null;
$format = null;
if (!empty($this->article->medium_id) && ($format = $this->orm->getImageFormatByKey('banner')) !== null) {
    $medium = $this->orm->getMediumById($this->article->medium_id);
}

$articleText = (strlen($this->article->teaser) > 0)? $this->article->teaser : $this->article->content;
$articleText = $this->ncm->convertFormattedText($articleText);
?>
<?php if ($this->article instanceof \Ubergeek\NanoCm\Article) : ?>
    <article>
        <h1><a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>"><?php echo $this->htmlEncode($this->article->headline); ?></a></h1>

        <?php if ($format != null && $medium != null) : ?>
            <a class="imglink <?php echo $this->htmlEncode($format->key); ?>" href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>">
                <img src="<?php echo $this->htmlConvUrl($medium->getImageUrl($format->key)); ?>"
                     class="<?php echo $this->htmlEncode($format->key); ?>"
                     title="<?php echo $this->htmlEncode($medium->title); ?>"
                    <?php if ($format->width > 0) echo "width=\"$format->width\""; ?>
                    <?php if ($format->height > 0) echo "height=\"$format->height\""; ?>></a>
        <?php endif; ?>

        <?php echo $articleText; ?>
        <?php if (strlen($this->article->teaser) > 0) : ?>
            <p class="readmore"><a class="readmore" href="<?php echo $this->htmlEncode($this->article->getArticleUrl()); ?>">Weiterlesen</a></p>
        <?php endif; ?>

        <div class="articlefooter">
            <p>Ver&ouml;ffentlicht von
                <?php echo $this->htmlEncode($this->orm->convertUserIdToName($this->article->author_id, false)); ?>
                am
                <?php echo $this->htmlEncode($this->article->publishing_timestamp->format('d.m.Y')); ?>&nbsp;&bullet;
                <a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>#comment">Kommentieren</a>&nbsp;&bullet;
                <a href="<?php echo $this->htmlEncode(
                    \Ubergeek\NanoCm\Util::getTweetThisUrl(
                        $this->frontController->createAbsoluteSiteLink(
                            $this->article->getArticleUrl()
                        ),
                        $this->article->headline
                    )
                ); ?>" target="_blank">Twittern</a>
            </p>
            <?php if (is_array($this->article->tags) && count($this->article->tags) > 0) : ?>
                Schlagworte:
                <ul class="taglist">
                    <?php foreach ($this->article->tags as $tag) : ?>
                        <li><a href="<?php echo $this->htmlConvUrl($this->article->getTagSearchUrl($tag)); ?>"><?php echo $this->htmlEncode($tag); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    </article>
<?php endif; ?>
