<?php
/* @var $this \Ubergeek\NanoCm\Module\CoreModule */
?>
<?php if ($this->article instanceof \Ubergeek\NanoCm\Article) : ?>
    <div class="spacing">
        <h1><a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>"><?php echo $this->htmlEncode($this->article->headline); ?></a></h1>

        <?php echo $this->convertTextWithFullMarkup($this->article->content); ?>

        <div class="articlefooter">
            <p>Ver&ouml;ffentlicht von
                <?php echo $this->htmlEncode($this->orm->convertUserIdToName($this->article->author_id, false)); ?>
                am
                <?php echo $this->htmlEncode($this->article->publishing_timestamp->format('d.m.Y')); ?>&nbsp;&bullet;
                <a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>#comment">Kommentieren</a>&nbsp;&bullet;
                <a href="<?php echo $this->htmlConvUrl($this->article->getEbookUrl()); ?>">ePub (beta)</a>&nbsp;&bullet;
                <a href="<?php echo $this->htmlEncode(
                    \Ubergeek\NanoCm\Util::getTweetThisUrl(
                        $this->frontController->createAbsoluteSiteLink(
                            $this->article->getArticleUrl()
                        ),
                        $this->article->headline
                    )
                ); ?>" target="_blank">Twittern</a>
            </p>
            <?php if (is_array($this->article->tags) && count($this->article->tags) > 0) : ?>
                Schlagworte:
                <ul class="taglist">
                    <?php foreach ($this->article->tags as $tag) : ?>
                        <li><a href="<?php echo $this->htmlConvUrl($this->article->getTagSearchUrl($tag)); ?>"><?php echo $this->htmlEncode($tag); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
