<?php if ($this->article instanceof \Ubergeek\NanoCm\Article) : ?>
    <div class="spacing">
        <h1><a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>"><?php echo $this->htmlEncode($this->article->headline); ?></a></h1>

        <?php echo $this->ncm->convertFormattedText($this->article->content); ?>

        <div class="articlefooter">
            Ver&ouml;ffentlicht von
            <?php echo $this->htmlEncode($this->orm->convertUserIdToName($this->article->author_id, false)); ?>
            am
            <?php echo $this->htmlEncode($this->article->publishing_timestamp->format('d.m.Y')); ?>&nbsp;&bullet;
            <a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>#comments">Kommentieren</a>&nbsp;&bullet;
            <a href="<?php echo $this->htmlEncode(
                \Ubergeek\NanoCm\Util::getTweetThisUrl(
                    $this->frontController->createAbsoluteSiteLink(
                        $this->article->getArticleUrl()
                    ),
                    $this->article->headline
                )
            ); ?>" target="_blank">Twittern</a>
        </div>
    </div>
<?php endif; ?>
