<?php
/* @var $medium \Ubergeek\NanoCm\Medium */
/* @var $format \Ubergeek\NanoCm\Media\ImageFormat */
/* @var $articleText string */

$medium = null;
$format = null;
if (!empty($this->article->medium_id) && ($format = $this->orm->getImageFormatByKey('thumb')) !== null) {
    $medium = $this->orm->getMediumById($this->article->medium_id);
}

$articleText = (strlen($this->article->teaser) > 0)? $this->article->teaser : $this->article->content;
$articleText = $this->ncm->convertFormattedText($articleText);
?>

<?php if ($this->article instanceof \Ubergeek\NanoCm\Article) : ?>
    <div class="spacing">
        <h1><a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>"><?php echo $this->htmlEncode($this->article->headline); ?></a></h1>

        <?php if ($format != null && $medium != null) : ?>
            <a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>">
                <img src="<?php echo $this->htmlConvUrl($medium->getImageUrl($format->key)); ?>"
                     class="<?php echo $this->htmlEncode($format->key); ?>"
                     title="<?php echo $this->htmlEncode($medium->title); ?>"
                     style="float: left; margin-right: 1rem; margin-top: 0.2rem; margin-bottom: 0.2rem"
                    <?php if ($format->width > 0) echo "width=\"$format->width\""; ?>
                    <?php if ($format->height > 0) echo "height=\"$format->height\""; ?>></a>
        <?php endif; ?>
        <?php echo $articleText; ?>
        <?php if (strlen($this->article->teaser) > 0) : ?>
            <p class="readmore"><a class="readmore" href="<?php echo $this->htmlEncode($this->article->getArticleUrl()); ?>">Weiterlesen</a></p>
        <?php endif; ?>

        <div class="articlefooter">
            Ver&ouml;ffentlicht von
            <?php echo $this->htmlEncode($this->orm->convertUserIdToName($this->article->author_id, false)); ?>
            am
            <?php echo $this->htmlEncode($this->article->publishing_timestamp->format('d.m.Y')); ?>&nbsp;&bullet;
            <a href="<?php echo $this->htmlConvUrl($this->article->getArticleUrl()); ?>#comments">Kommentieren</a>&nbsp;&bullet;
            <a href="<?php echo $this->htmlEncode(
                \Ubergeek\NanoCm\Util::getTweetThisUrl(
                    $this->frontController->createAbsoluteSiteLink(
                        $this->article->getArticleUrl()
                    ),
                    $this->article->headline
                )
            ); ?>" target="_blank">Twittern</a>
        </div>
    </div>
<?php endif; ?>

