<?php
/* @var $this \Ubergeek\NanoCm\Module\CoreModule */
/* @var $medium \Ubergeek\NanoCm\Medium */
/* @var $format \Ubergeek\NanoCm\Media\ImageFormat */
/* @var $articleText string */

$medium = null;
$format = null;
if (!empty($this->article->medium_id) && ($format = $this->orm->getImageFormatByKey('banner')) !== null) {
    $medium = $this->orm->getMediumById($this->article->medium_id);
}
?>
<figure>
    <div class="figurecontainer" style="max-width: 600px">
        <div class="imgcontainer">
            <a href="/media/cd215eccfd5d84c60f446ba3238b54d6/image/original/" data-lightbox="preview" data-title="Der Stier und das M&auml;dchen">
                <img src="/media/cd215eccfd5d84c60f446ba3238b54d6/image/preview/" />
            </a>
            <div class="attribution">Einfacher Copyright-Hinweis mit <a href="javascript:void(0);">Quelle</a>
                und etwas mehr Text, der im Normalfall &uuml;ber mehr als eine Zeile l&auml;uft.</div>
        </div>
        <div class="caption shadow">
            <figcaption>Beschreibung zu diesem Bild, die in diesem Fall tats&auml;chlich auch
                mal mehrzeilig ist. Dum di dum di dum. Sogar mit <a href="javascript:void(0)">Link</a>.</figcaption>
        </div>
    </div>
</figure>
