<?php
/* @var $this \Ubergeek\NanoCm\Module\AbstractModule */
$vid = $this->getVar('converter.youtube.vid');
?>
<div class="youtube-preview" data-vid="<?php echo $this->htmlEncode($vid); ?>">
    <a href="https://www.youtube.com/watch?v=<?php echo $this->htmlEncode($vid); ?>" target="_blank">
        <img src="<?php echo $this->convUrl($this->getYoutubeThumbnailUrl($vid, 'ytthumb')); ?>" alt="Youtube">
    </a>
</div>