<?php
use Ubergeek\NanoCm\ContentConverter\Plugin\PluginOptions;
use Ubergeek\NanoCm\Media\ImageFormat;
use Ubergeek\NanoCm\Medium;
use Ubergeek\NanoCm\Module\AbstractModule;

/* @var $this AbstractModule */
/* @var $params PluginOptions */

$folderId = $params->arguments->getValue('folderid');
$folder = $params->extended->getValue('folder');
$media = $params->extended->getValue('media');
$format = $params->extended->getValue('format');
?>

<?php if ($format instanceof ImageFormat && $folder instanceof Medium && is_array($media) && count($media) > 0) : ?>
    <div class="shadow slideshow">
        <div class="frame">
            <div class="images">
                <?php foreach ($media as $i => $medium) : ?>
                    <div class="image">
                        <a href="<?php echo $this->htmlConvUrl($this->getImageUrl($medium, 'original')); ?>" data-lightbox="preview-album_<?php echo $folderId; ?>" data-title="<?php echo $this->htmlEncode($medium->title); ?>">
                            <img loading="lazy" src="<?php echo $this->htmlConvUrl($this->getImageUrl($medium, $format->key)); ?>"
                                 width="<?php echo $format->width; ?>" height="<?php echo $format->height; ?>"
                                 srcset="<?php echo $this->htmlConvUrl($this->getImageUrl($medium, $format->key, 2)); ?> 2x" alt="" title="">
                        </a>
                        <?php if (strlen($medium->attribution) > 0) : ?>
                            <div class="attribution"><?php echo $this->convertTextWithBasicMarkup($medium->attribution); ?></div>
                        <?php endif; ?>
                        <?php if (strlen($medium->description) > 0) : ?>
                            <div class="caption">
                                <?php echo $this->convertTextWithBasicMarkup($medium->description); ?>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php else : ?>
    <p>[Wrong data]</p>
<?php endif; ?>