<div class="container" id="div_privacy" style="position: fixed; bottom: 2em; right: 0; left: 0; z-index: 100; margin-left: auto; margin-right: auto">
    <div class="alert">
        <p style="margin: 0.5em">
            <span><strong>Diese Seite verwendet Cookies.</strong><br>
            Auf dieser Website werden sogenannte Session-Cookies verwendet, um wiederkehrende
            Besucher zu erkennen. Ben&ouml;tigt wird diese Funktion, um Artikel zu kommentieren
            und um sich an der Seite anzumelden (nur Redakteure).
            Wenn Sie mit der Nutzung von Cookies nicht einverstanden sind, k&ouml;nnen Sie
            die Seite problemlos nutzen, lediglich die oben genannten Funktion sind dann
            nicht verf&uuml;gbar. Da wir eine Ablehnung nicht speichern k&ouml;nnen bzw.
            Sie bei folgenden Seitenabrufen nicht wiedererkennen, erscheint dieser Hinweis
            in diesem Fall immer wieder.</span>
        </p>
        <p style="margin: 0.5em">
            <input type="button" class="button button-small" id="button_privacy_deny" value="Cookies ablehnen">
            <input type="button" class="button button-small" id="button_privacy_accept" value="Cookies akzeptieren">
        </p>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        ncmPublic.initPrivacyForm();
    });
</script>
