<?php  /* @var $this \Ubergeek\NanoCm\Module\AdminSettingsModule */ ?>
<div class="container">
    <form onsubmit="settings.refresh(); return false;">
        <h1>Erweiterte Einstellungen verwalten</h1>

        <div class="toolbar">
            <span class="left">
                <a id="button_add" class="button" href="javascript:void(0)" role="button" title="Einstellung hinzuf&uuml;gen">
                    <img src="/ncm/img/fatcow/16/add.png" alt="" width="16" height="16" />Neu
                </a>
                <a id="button_edit" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlte Einstellung bearbeiten">Bearbeiten</a>
                <a id="button_delete" class="button button-secondary" href="javascript:void(0)" role="button" title="Ausgew&auml;hlte Einstellungen l&ouml;schen">L&ouml;schen</a>
            </span>
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="/ncm/img/spin.gif" />

                <label for="input_searchterm">Suche</label>
                <input id="input_searchterm" type="text" autofocus="autofocus" />

                <a class="button spaceleft" role="button" id="button_refresh" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img src="/ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16" />Aktualisieren
                </a>
            </span>
            <input type="hidden" id="input_searchPage" name="searchPage" value="<?php echo intval($this->searchPage); ?>" />
        </div>

        <div id="placeholder_settings" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    function Settings() {
        let app = this;
        app.page = $('#input_searchPage').val();

        app.init = function() {
            $('#button_refresh').click(function() {
                app.refresh();
            });

            $('#button_add').click(function() {
                app.editSetting('');
            });

            $('#button_edit').click(function() {
                app.editSelected();
            });

            $('#button_delete').click(function() {
                app.deleteSelected();
            });

            app.refresh();
        };

        /**
         * Aktualisiert die angezeigte Seite der Einstellungen
         * @param {int} page
         */
        app.refresh = function(page) {
            ncm.showDefaultLoadingIndicator();
            if (typeof page === 'undefined') page = app.page;

            $.ajax('/admin/settings/html/list', {
                cache:      false,
                type:       'GET',
                dataType:   'HTML',
                data: {
                    searchterm: $('#input_searchterm').val(),
                    searchPage: page
                }
            }).done(function(data) {
                $('#placeholder_settings .content').html(data);
                $('.selectall').click(function() {
                    ncm.toggleAllRowsSelection(this);
                });
            }).always(function() {
                ncm.hideDefaultLoadingIndicator();
            });
        };

        app.editClickedSetting = function(clickedLink) {
            let key = $(clickedLink).attr('data-key');
            app.editSetting(key);
        };

        app.editSetting = function(key) {
            let dlg = new ncm.InlinePopup(
                '/admin/settings/html/edit/' + key, {
                    key: key
                }, {
                    headline:   'Einstellung bearbeiten',
                    width:      500,
                    height:     200
                }, {
                    cancel: {
                        caption: 'Abbrechen',
                        clicked: function() {
                            dlg.close();
                        }
                    },
                    save: {
                        caption: 'Speichern',
                        clicked: function() {
                            $.ajax('/admin/settings/ajax/save', {
                                cache: false,
                                type: 'POST',
                                dataType: 'JSON',
                                data:   {
                                    key:    $('#edit_setting_key').val(),
                                    value:  $('#edit_setting_value').val(),
                                    params: $('#edit_setting_params').val()
                                }
                            }).always(function() {
                                dlg.close();
                                app.refresh();
                            });
                        }
                    }
                }
            );
        };

        /**
         * Ruft die Bearbeitungsmaske für die erste ausgewählte Einstellung auf
         */
        app.editSelected = function() {
            let id = ncm.getFirstSelectedRowId();
            if (id != null) {
                app.editSetting(id);
            }
        };

        /**
         * Löscht alle ausgewählten Einstellungen
         */
        app.deleteSelected = function() {
            let ids = ncm.getSelectedRowIds();
            if (ids.length > 0) {
                if (confirm('Wollen Sie die ausgewählten Einstellungen wirklich endgültig löschen?')) {
                    ncm.showDefaultLoadingIndicator();
                    $.ajax('/admin/settings/ajax/delete', {
                        cache: false,
                        type: 'GET',
                        dataType: 'JSON',
                        data: {
                            keys: ids
                        }
                    }).always(function () {
                        ncm.hideDefaultLoadingIndicator();
                        app.refresh();
                    });
                }
            }
        };

        app.init();
    }

    $(document).ready(function() {
        module = new Settings();
    });
</script>