<?php
/**
 * NanoCM
 * Copyright (C) 2017 - 2018 André Gewert <agewert@ubergeek.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

/* @var $this \Ubergeek\NanoCm\Module\AdminStatsModule */
?>

<div class="container spacing">
    <h1>Statistiken</h1>
    <input type="hidden" id="input_searchPage" name="searchPage" value="<?php echo intval($this->searchPage); ?>" />
</div>

<?php if (!$this->statsEnabled) : ?>
    <div class="container spacing">
        <div class="msgnote">
            <em>Hinweis:</em> Das F&uuml;hren von Zugriffsstatistiken ist aktuell ausgeschaltet.<br>
            Aktivieren Sie diese Funktion in den <a href="/admin/settings/?searchTerm=system.stats">Einstellungen</a>.
        </div>
    </div>
<?php endif; ?>

<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">
        <div class="toolbar">
            <span class="left">
                <a id="button_add" class="button" href="/admin/stats/" role="button" title="Zusammengefasste Statistiken anzeigen">
                    <img src="/ncm/img/fatcow/16/directory_listing.png" alt="" width="16" height="16">&Uuml;bersicht
                </a>
            </span>
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="/ncm/img/spin.gif" />

                <label for="inputsearchYear">Jahr</label>
                <input id="input_searchYear" style="width: 80px" type="text" value="<?php echo $this->htmlEncode($this->searchYear); ?>" />

                <label for="select_searchMonth" class="spaceleft">Monat</label>
                <select id="select_searchMonth">
                    <?php for ($i = 1; $i <= 12; $i++) : ?>
                        <option value="<?php echo $i; ?>" <?php if ($this->searchMonth == $i) echo 'selected="selected"'; ?>>
                            <?php echo DateTime::createFromFormat('!m', $i)->format('F'); ?>
                        </option>
                    <?php endfor; ?>
                </select>

                <a id="button_refresh" class="button spaceleft" role="button" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="/ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        </div>

        <div id="placeholder_accesslog" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    function AccessLog() {
        let app = this;
        app.page = $('#input_searchPage').val();

        /**
         * Initialisiert Event-Handler etc.
         */
        app.init = function() {
            $('#button_refresh').click(function() {
                app.refresh();
            });
            app.refresh();
        };

        /**
         * Aktualisiert den angezeigten Ausschnitt aus dem AccessLog
         */
        app.refresh = function(page) {
            ncm.showDefaultLoadingIndicator();
            if (typeof page === 'undefined') page = app.page;

            $.ajax('/admin/stats/html/listaccesslog', {
                cache:      false,
                type:       'GET',
                dataType:   'HTML',
                data: {
                    searchYear:         $('#input_searchYear').val(),
                    searchMonth:        $('#select_searchMonth').val(),
                    searchPage:         page
                }
            }).done(function(data) {
                $('#placeholder_accesslog .content').html(data);
            }).always(function() {
                ncm.hideDefaultLoadingIndicator();
                $('#input_searchYear').focus();
            });
        };
        app.init();
    }

    $(document).ready(function() {
        module = new AccessLog();
    });
</script>