<?php
/* @var $this \Ubergeek\NanoCm\Module\AdminInstallationModule */
?>
<div class="mx-4 my-2">
    <div class="row">
        <div class="info">
            <p>Mit dieser Funktion wird ein neues Backup der aktuellen Installation erstellt.
            Teil des Backups sind auch die Datenbanken, d. h. alle Inhalte und Einstellungen.
                Jedes Backup kann zu einem späteren Zeitpunkt wiederhergestellt werden.</p>
            <p class="mb-0">Der Dateiname f&uuml;r ein neues Backup wird automatisch vergeben.</p>
        </div>
    </div>
</div>
