<?php
/* @var $this \Ubergeek\NanoCm\Module\AdminInstallationModule */
?>
<script type="text/javascript" src="ncm/js/Installation.js"></script>
<div class="container spacing">
    <div class="toolbar">
        <span class="left">
            <a id="button_create" class="button" href="javascript:void(0);" role="button" title="Neues Backup erstellen">
                <img src="ncm/img/fatcow/16/backup_wizard.png" alt="" width="16" height="16">Backup erstellen
            </a>
            <a id="button_restore" class="button" href="javascript:void(0);" role="button" title="Bestehendes Backup wiederherstellen">
                <img src="ncm/img/fatcow/16/site_backup_and_restore.png" alt="" width="16" height="16">Wiederherstellen
            </a>
            <a id="button_delete" class="button button-secondary" href="javascript:void(0);" role="button" title="Bestehendes Backup löschen">
                <img src="ncm/img/fatcow/16/delete.png" alt="" width="16" height="16">L&ouml;schen
            </a>
        </span>
        <span class="right" style="float: right; vertical-align: middle">
                <img class="spinner" id="toolbar_spinner" src="ncm/img/spin.gif">

                <a class="button spaceleft" role="button" id="button_refresh" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        <input type="hidden" id="input_searchPage" name="searchPage" value="<?php echo (int)$this->searchPage; ?>" />
    </div>

    <div id="placeholder_installation" class="placeholder">
        <div class="blanker"></div>
        <div class="content"></div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        module = new Installation();
    });
</script>