<?php
/* @var $this \Ubergeek\NanoCm\Module\AdminStatsModule */
?>
<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">
        <h1>Statistiken</h1>

        <div class="toolbar">
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="/ncm/img/spin.gif" />

                <label for="inputsearchYear">Jahr</label>
                <input id="input_searchYear" style="width: 80px" type="text" value="<?php echo $this->htmlEncode($this->searchYear); ?>" />

                <label for="select_searchMonth" class="spaceleft">Monat</label>
                <select id="select_searchMonth">
                    <?php for ($i = 1; $i <= 12; $i++) : ?>
                        <option value="<?php echo $i; ?>" <?php if ($this->searchMonth == $i) echo 'selected="selected"'; ?>>
                            <?php echo DateTime::createFromFormat('!m', $i)->format('F'); ?>
                        </option>
                    <?php endfor; ?>
                </select>

                <a id="button_refresh" class="button spaceleft" role="button" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="/ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        </div>

        <div id="placeholder_stats" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    function Lists() {
        let app = this;

        /**
         * Initialisiert Event-Handler etc.
         */
        app.init = function() {
            $('#button_refresh').click(function() {
                app.refresh();
            });
            app.refresh();
        };

        /**
         * Aktualisiert die Liste der Pages
         */
        app.refresh = function() {
            ncm.showDefaultLoadingIndicator();

            $.ajax('/admin/stats/html/list', {
                cache:      false,
                type:       'GET',
                dataType:   'HTML',
                data: {
                    searchYear:         $('#input_searchYear').val(),
                    searchMonth:        $('#select_searchMonth').val()
                }
            }).done(function(data) {
                $('#placeholder_stats .content').html(data);
            }).always(function() {
                ncm.hideDefaultLoadingIndicator();
                $('#input_searchYear').focus();
            });
        };
        app.init();
    }

    $(document).ready(function() {
        module = new Lists();
    });
</script>