<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminArticleseriesModule */
    use Ubergeek\NanoCm\StatusCode;
?>
<script type="text/javascript" src="ncm/js/Definitions.js"></script>
<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">
        <input type="hidden" id="input_searchPage" name="searchPage" value="<?php echo intval($this->searchPage); ?>" />

        <div class="toolbar">
            <span class="left">
                <a id="button_add" class="button" href="javascript:void(0)" role="button" title="Definition hinzuf&uuml;gen">
                    <img src="ncm/img/fatcow/16/add.png" alt="" width="16" height="16">Neu
                </a>
                <a id="button_edit" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlte Definition bearbeiten">
                    <img src="ncm/img/fatcow/16/toolbar_edit.png" alt="" width="16" height="16">Bearbeiten
                </a>
                <a id="button_delete" class="button button-secondary" href="javascript:void(0)" role="button" title="Ausgew&auml;hlte Definition l&ouml;schen">
                    <img src="ncm/img/fatcow/16/toolbar_delete.png" alt="" width="16" height="16">L&ouml;schen
                </a>
            </span>
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="ncm/img/spin.gif">

                <label for="input_searchTerm">Suche</label>
                <input id="input_searchTerm" type="text" autofocus="autofocus" value="<?php echo $this->htmlEncode($this->searchTerm); ?>">

                <a class="button spaceleft" role="button" id="button_refresh" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        </div>

        <div id="placeholder_definitions" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        module = new Definitions();
    });
</script>