<?php /* @var $this \Ubergeek\NanoCm\Module\AdminArticlesModule */

use Ubergeek\NanoCm\StatusCode; ?>
<div class="container">
    <form>
        <h1>Artikel verwalten</h1>

        <div class="toolbar">
            <span class="left">
                <a name="" id="" class="button" href="#" role="button" title="Artikel hinzuf&uuml;gen">
                    <img src="/ncm/img/fatcow/16/add.png" alt="" width="16" height="16" />Neu
                </a>
                <a name="" id="" class="button" href="#" role="button" title="Ausgew&auml;hlten Artikel bearbeiten">Bearbeiten</a>
                <a name="" id="" class="button button-secondary" href="#" role="button" title="Ausgew&auml;hlte Artikel l&ouml;schen">L&ouml;schen</a>
            </span>
            <span class="right" style="float: right; vertical-align: middle">
                <img class="spinner" id="toolbar_spinner" src="/ncm/img/spin.gif" />

                <label for="input_searchterm">Suche</label>
                <input id="input_searchterm" type="text" />

                <label for="select_status" class="spaceleft">Status</label>
                <select id="select_status">
                    <option value="">- Alle -</option>
                    <?php foreach ($this->availableStatusCodes as $code) : ?>
                        <option value="<?php echo $code; ?>"><?php echo StatusCode::convertStatusId($code); ?></option>
                    <?php endforeach; ?>
                </select>

                <input type="button" class="button spaceleft" value="Aktualisieren" id="button_refresh" />
            </span>
        </div>

        <div id="placeholder_articles" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>

    </form>
</div>
<script type="text/javascript">
    function Articles() {
        var app = this;

        app.showLoadingIndicator = function() {
            $('#toolbar_spinner').addClass('loading');
            $('.placeholder').addClass('loading');
        };

        app.hideLoadingIndicator = function() {
            $('#toolbar_spinner').removeClass('loading');
            $('.placeholder').removeClass('loading');
        };

        app.refresh = function(page) {
            app.showLoadingIndicator();
            if (typeof page === 'undefined') {
                page = 1;
            }

            $.ajax('/admin/articles/ajax/list', {
                cache:      false,
                type:       'GET',
                dataType:   'HTML',
                data:       {
                    searchterm: $('#input_searchterm').val(),
                    status:     $('#select_status').val(),
                    page:       page
                }
            }).done(function(data) {
                $('#placeholder_articles .content').html(data);
                $('.selectall').click(function() {
                    ncm.toggleAllRowsSelection(this);
                });
            }).always(function() {
                app.hideLoadingIndicator();
            });
        };

        $('#button_refresh').click(function() {
            app.refresh();
        });
    }

    $(document).ready(function() {
        var articles = new Articles();
        articles.refresh();
    });
</script>