<?php /* @var $this \Ubergeek\NanoCm\Module\AdminStatsModule */ ?>
<h2>Abgerufene URLs</h2>
<table class="list">
    <thead>
        <tr>
            <th>URL</th>
            <th width="10%" class="textright">Abrufe</th>
        </tr>
    </thead>
    <tbody>
        <?php if (is_array($this->statsUrls) && count($this->statsUrls) > 0) : ?>
            <?php $sum = 0; ?>
            <?php foreach ($this->statsUrls as $url) : ?>
                <tr>
                    <td><?php echo $this->htmlEncode($url['url']); ?></td>
                    <td class="textright pre"><?php echo $url['sumcount']; ?></td>
                </tr>
                <?php $sum += $url['sumcount']; ?>
            <?php endforeach; ?>
            <tr>
                <th>Summe</th>
                <th class="textright pre">
                    <?php echo $sum; ?>
                </th>
            </tr>
        <?php else : ?>
            <tr class="noresult">
                <td colspan="2">
                    &mdash;&nbsp;Keine Ergebnisse&nbsp;&mdash;
                </td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>

<h2>Browser</h2>
<table class="list">
    <thead>
    <tr>
        <th>Browser</th>
        <th width="10%" class="textright">Abrufe</th>
    </tr>
    </thead>
    <tbody>
    <?php if (is_array($this->statsBrowsers) && count($this->statsBrowsers) > 0) : ?>
        <?php $sum = 0; ?>
        <?php foreach ($this->statsBrowsers as $browser) : ?>
            <tr>
                <td><?php echo $this->htmlEncode($browser['browsername']); ?></td>
                <td class="textright pre"><?php echo $browser['sumcount']; ?></td>
            </tr>
            <?php $sum += $browser['sumcount']; ?>
        <?php endforeach; ?>
        <tr>
            <th>Summe</th>
            <th class="textright pre">
                <?php echo $sum; ?>
            </th>
        </tr>
    <?php else : ?>
        <tr class="noresult">
            <td colspan="2">
                &mdash;&nbsp;Keine Ergebnisse&nbsp;&mdash;
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>

<h2>Betriebssysteme</h2>
<table class="list">
    <thead>
    <tr>
        <th>Betriebssystem</th>
        <th width="10%" class="textright">Abrufe</th>
    </tr>
    </thead>
    <tbody>
    <?php if (is_array($this->statsOses) && count($this->statsOses) > 0) : ?>
        <?php $sum = 0; ?>
        <?php foreach ($this->statsOses as $os) : ?>
            <tr>
                <td><?php echo $this->htmlEncode($os['osname']); ?></td>
                <td class="textright pre"><?php echo $os['sumcount']; ?></td>
            </tr>
            <?php $sum += $os['sumcount']; ?>
        <?php endforeach; ?>
        <tr>
            <th>Summe</th>
            <th class="textright pre"><?php echo $sum; ?></th>
        </tr>
    <?php else : ?>
        <tr class="noresult">
            <td colspan="2">
                &mdash;&nbsp;Keine Ergebnisse&nbsp;&mdash;
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>

<h2>Herkunftsländer</h2>
<table class="list">
    <thead>
    <tr>
        <th>Land</th>
        <th>Region</th>
        <th width="10%" class="textright">Abrufe</th>
    </tr>
    </thead>
    <tbody>
    <?php if (is_array($this->statsCountry) && count($this->statsCountry) > 0) : ?>
        <?php $sum = 0; ?>
        <?php foreach ($this->statsCountry as $country) : ?>
            <tr>
                <td><?php echo $this->htmlEncode($country['country']); ?></td>
                <td><?php echo $this->htmlEncode($country['regionname']); ?></td>
                <td class="textright pre"><?php echo $country['sumcount']; ?></td>
            </tr>
            <?php $sum += $country['sumcount']; ?>
        <?php endforeach; ?>
        <tr>
            <th>Summe</th>
            <th colspan="2" class="textright pre"><?php echo $sum; ?></th>
        </tr>
    <?php else : ?>
        <tr class="noresult">
            <td colspan="3">
                &mdash;&nbsp;Keine Ergebnisse&nbsp;&mdash;
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>

<h2>Sessions</h2>
<table class="list">
    <thead>
    <tr>
        <th>Eindeutige Sessions</th>
        <th width="10%" class="textright">Anzahl</th>
    </tr>
    </thead>
    <tbody>
    <?php if (is_array($this->statsSessionId) && count($this->statsSessionId) > 0) : ?>
        <?php foreach ($this->statsSessionId as $sessionId) : ?>
            <tr>
                <td></td>
                <td class="textright pre"><?php echo $sessionId['c']; ?></td>
            </tr>
        <?php endforeach; ?>
    <?php else : ?>
        <tr class="noresult">
            <td colspan="3">
                &mdash;&nbsp;Keine Ergebnisse&nbsp;&mdash;
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>