<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminPagesModule */
    use Ubergeek\NanoCm\StatusCode;
?>
<script type="text/javascript" src="ncm/js/Pages.js"></script>
<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">
        <input type="hidden" id="input_searchPage" name="searchPage" value="<?php echo intval($this->searchPage); ?>" />

        <div class="toolbar">
            <span class="left">
                <a id="button_add" class="button" href="admin/pages/edit/" role="button" title="Seite hinzuf&uuml;gen">
                    <img src="ncm/img/fatcow/16/page_add.png" srcset="ncm/img/fatcow/32/page_add.png 2x" alt="" width="16" height="16">Neu
                </a>
                <a id="button_edit" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlte Seite bearbeiten">
                    <img src="ncm/img/fatcow/16/page_edit.png" srcset="ncm/img/fatcow/32/page_edit.png 2x" alt="" width="16" height="16">Bearbeiten
                </a>
                <a id="button_lock" class="button" href="javascript:void(0)" role="button" title="Ausgew&auml;hlte Seiten sperren">
                    <img src="ncm/img/fatcow/16/lock.png" srcset="ncm/img/fatcow/32/lock.png 2x" alt="" width="16" height="16">Sperren
                </a>
                <a id="button_delete" class="button button-secondary" href="javascript:void(0);" role="button" title="Ausgew&auml;hlte Seiten l&ouml;schen">
                    <img src="ncm/img/fatcow/16/page_delete.png" srcset="ncm/img/fatcow/32/page_delete.png 2x" alt="" width="16" height="16">L&ouml;schen
                </a>
            </span>
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="ncm/img/spin.gif" />

                <label for="input_searchTerm">Suche</label>
                <input id="input_searchTerm" type="text" autofocus="autofocus" value="<?php echo $this->htmlEncode($this->searchTerm); ?>" />

                <label for="select_searchStatusCode" class="spaceleft">Status</label>
                <select id="select_searchStatusCode">
                    <option value="">- Alle -</option>
                    <?php foreach ($this->availableStatusCodes as $code) : ?>
                        <option value="<?php echo $code; ?>" <?php if ($this->searchStatusCode != '' && $this->searchStatusCode == $code) echo ' selected="selected"'; ?>><?php echo StatusCode::convertStatusId($code); ?></option>
                    <?php endforeach; ?>
                </select>

                <a id="button_refresh" class="button spaceleft" role="button" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="ncm/img/fatcow/16/arrow_refresh.png" srcset="ncm/img/fatcow/32/arrow_refresh.png 2x" alt="" width="16" height="16">
                </a>
            </span>
        </div>

        <div id="placeholder_pages" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        module = new Pages();
    });
</script>