<?php
/* @var $this \Ubergeek\NanoCm\Module\AdminArticleseriesModule */
use Ubergeek\NanoCm\StatusCode;
?>
<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">
        <h1>Definitionen verwalten</h1>
        <input type="hidden" id="input_searchPage" name="searchPage" value="<?php echo intval($this->searchPage); ?>" />

        <div class="toolbar">
            <span class="left">
                <a id="button_add" class="button" href="javascript:void(0)" role="button" title="Definition hinzuf&uuml;gen">
                    <img src="/ncm/img/fatcow/16/add.png" alt="" width="16" height="16">Neu
                </a>
                <a id="button_edit" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlte Definition bearbeiten">
                    <img src="/ncm/img/fatcow/16/toolbar_edit.png" alt="" width="16" height="16">Bearbeiten
                </a>
                <a id="button_delete" class="button button-secondary" href="javascript:void(0)" role="button" title="Ausgew&auml;hlte Definition l&ouml;schen">
                    <img src="/ncm/img/fatcow/16/toolbar_delete.png" alt="" width="16" height="16">L&ouml;schen
                </a>
            </span>
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="/ncm/img/spin.gif">

                <label for="input_searchTerm">Suche</label>
                <input id="input_searchTerm" type="text" autofocus="autofocus" value="<?php echo $this->htmlEncode($this->searchTerm); ?>">

                <a class="button spaceleft" role="button" id="button_refresh" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="/ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        </div>

        <div id="placeholder_definitions" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    function Definitions() {
        let app = this;
        app.page = $('#input_searchPage').val();

        app.init = function() {
            $('#button_refresh').click(function() {
                app.refresh();
            });

            $('#button_add').click(function() {
                app.editDefinition('', '');
            });

            $('#button_edit').click(function() {
                app.editSelected();
            });

            $('#button_delete').click(function() {
                app.deleteSelected();
            });

            app.refresh();
        };

        /**
         * Aktualisiert die angezeigte Seite der Einstellungen
         * @param {int} page
         */
        app.refresh = function(page) {
            ncm.showDefaultLoadingIndicator();
            if (typeof page === 'undefined') page = app.page;

            $.ajax('/admin/definitions/html/list', {
                cache:      false,
                type:       'GET',
                dataType:   'HTML',
                data: {
                    searchTerm: $('#input_searchTerm').val(),
                    searchPage: page
                }
            }).done(function(data) {
                $('#placeholder_definitions .content').html(data);
                $('.selectall').click(function() {
                    ncm.toggleAllRowsSelection(this);
                });
            }).always(function() {
                ncm.hideDefaultLoadingIndicator();
            });
        };

        app.editClickedDefinition = function(clickedLink) {
            let definitiontype = $(clickedLink).attr('data-definitiontype');
            let key = $(clickedLink).attr('data-key');
            app.editDefinition(definitiontype, key);
        };

        app.editDefinition = function(definitiontype, key) {
            let dlg = new ncm.InlinePopup(
                '/admin/definitions/html/edit/', {
                    definitiontype: definitiontype,
                    key: key
                }, {
                    headline:   (definitiontype == '' && key == '')? 'Definition anlegen' : 'Definition bearbeiten',
                    width:      500,
                    height:     320,
                    loaded:     function() {
                        ncm.focusDefaultElement();
                    }
                }, {
                    cancel: {
                        caption: 'Abbrechen',
                        clicked: function() {
                            dlg.close();
                        }
                    },
                    save: {
                        caption: 'Speichern',
                        clicked: function() {
                            ncm.showDefaultLoadingIndicator();
                            $.ajax('/admin/definitions/ajax/save', {
                                cache: false,
                                type: 'POST',
                                dataType: 'JSON',
                                data:   {
                                    definitiontype:     $('#edit_definition_definitiontype').val(),
                                    key:                $('#edit_definition_key').val(),
                                    title:              $('#edit_definition_title').val(),
                                    value:              $('#edit_definition_value').val(),
                                    parameters:         $('#edit_definition_parameters').val()
                                }
                            }).always(function() {
                                ncm.hideDefaultLoadingIndicator();
                                dlg.close();
                                app.refresh();
                            });
                        }
                    }
                }
            );
        };

        /**
         * Ruft die Bearbeitungsmaske für die erste ausgewählte Einstellung auf
         */
        app.editSelected = function() {
            let id = ncm.getFirstSelectedRowId();
            if (id != null) {
                app.editSetting(id.split(' ', 1)[0], id.split(' ', 1)[1]);
            }
        };

        /**
         * Löscht alle ausgewählten Einstellungen
         */
        app.deleteSelected = function() {
            let ids = ncm.getSelectedRowIds();
            if (ids.length > 0) {
                if (confirm('Wollen Sie die ausgewählten Einstellungen wirklich endgültig löschen?')) {
                    ncm.showDefaultLoadingIndicator();
                    $.ajax('/admin/definitions/ajax/delete', {
                        cache: false,
                        type: 'GET',
                        dataType: 'JSON',
                        data: {
                            keys: ids
                        }
                    }).always(function () {
                        ncm.hideDefaultLoadingIndicator();
                        app.refresh();
                    });
                }
            }
        };

        app.init();
    }

    $(document).ready(function() {
        module = new Definitions();
    });
</script>