<?php /* @var $this \Ubergeek\NanoCm\Module\AdminDashboardModule */

use Ubergeek\NanoCm\Setting; ?>
<div class="container spacing">
    <h1>&Uuml;bersicht</h1>
</div>
<?php if ($this->isSiteDbAccessible) : ?>
    <div class="container spacing">
        <div class="error" style="border: solid red 5px; padding: 1em; font-size: 1.5rem; border-radius: 5px; margin-bottom: 1rem; margin-top: 1rem">
            <em>ACHTUNG:</em> Die Systemdatenbank ist &uuml;ber den Webserver von au&szlig;en erreichbar!<br>
            Bitte &uuml;berpr&uuml;fen Sie unbedingt die Server-Einstellungen! Andernfalls sind s&auml;mtliche
            Daten der Website, einschlie&szlig;lich der Benutzerkonten und nicht freigeschalteter Inhalte f&uuml;r
            jedermann zug&auml;nglich!
        </div>
    </div>
<?php endif; ?>
<div class="container spacing">
    <h2>Kennzahlen</h2>
</div>
<div class="container">
    <div class="column-4 spacing">
        <table class="list" style="margin-top: 0">
            <tr>
                <th colspan="2">Grunddaten Website</th>
            </tr>
            <tr>
                <td>Name der Site</td>
                <td><?php echo $this->htmlEncode($this->getSiteTitle()); ?></td>
            </tr>
            <tr>
                <td>Sprache der Site</td>
                <td><?php echo $this->htmlEncode($this->orm->getSettingValue(Setting::SYSTEM_LANG)); ?></td>
            </tr>
            <tr>
                <td>Template</td>
                <td><?php echo $this->htmlEncode($this->orm->getSettingValue(Setting::SYSTEM_TEMPLATE_PATH)); ?></td>
            </tr>
            <tr>
                <td>Webmaster-Name</td>
                <td><?php echo $this->htmlEncode($this->orm->getSettingValue(Setting::SYSTEM_WEBMASTER_NAME)); ?></td>
            </tr>
            <tr>
                <td>Webmaster-Mail</td>
                <td><?php echo $this->htmlEncode($this->orm->getSettingValue(Setting::SYSTEM_WEBMASTER_EMAIL)); ?></td>
            </tr>
        </table>
    </div>
    <div class="column-4 spacing">
        <table class="list" style="margin-top: 0">
            <tr>
                <th colspan="2">Kennzahlen</th>
            </tr>
            <tr>
                <td>Anzahl freigeschalteter Artikel</td>
                <td class="textright pre"><?php echo $this->formatInt($this->numberOfReleasedArticles); ?></td>
            </tr>
            <tr>
                <td>Anzahl freigeschalteter Kommentare</td>
                <td class="textright pre"><?php echo $this->formatInt($this->numberOfActiveComments); ?></td>
            </tr>
            <tr>
                <td>Anzahl nicht freigeschalteter Kommentare</td>
                <td class="textright pre"><?php echo $this->formatInt($this->numberOfInactiveComments); ?></td>
            </tr>
            <tr>
                <td>Zu moderierende Kommentare</td>
                <td class="textright pre"><?php echo $this->formatInt($this->numberOfUnmoderatedComments); ?></td>
            </tr>
            <tr>
                <td>Anzahl Mediendateien</td>
                <td class="textright pre">0</td>
            </tr>
        </table>
    </div>
    <div class="column-4 spacing">
        <div>
            <a class="button" href="/admin/articles/edit/" role="button" title="Neuen Artikel schreiben" style="width: 50%">
                <img src="/ncm/img/fatcow/16/page_add.png" alt="" width="16" height="16">Neuen Artikel schreiben
            </a>
        </div>
        <div style="margin-top: 0.5em"></div>
            <a class="button" href="/admin/comments/?searchStatusCode=<?php echo \Ubergeek\NanoCm\StatusCode::MODERATION_REQUIRED; ?>" role="button" title="Kommentare moderieren" style="width: 50%">
                <img src="/ncm/img/fatcow/16/accept_button.png" alt="" width="16" height="16">Kommentare moderieren
                <?php if ($this->numberOfUnmoderatedComments > 0) : ?>
                    <span class="badge"><?php echo $this->numberOfUnmoderatedComments; ?></span>
                <?php endif; ?>
            </a>
        </div>
    </div>

    <div class="container">
        <div class="column-4 spacing">
            <h2>Inhaltsverwaltung</h2>
            <ul class="inlinemenu">
                <li><a href="/admin/articles/">Artikel</a></li>
                <li><a href="/admin/comments/">Kommentare</a></li>
                <li><a href="/admin/articleseries/">Artikelserien</a></li>
                <li><a href="/admin/pages/">Seiten</a></li>
                <li><a href="/admin/lists/">Listen</a></li>
                <li><a href="/admin/media/">Medien</a></li>
            </ul>
        </div>
        <div class="column-4 spacing">
            <h2>Erweiterte Verwaltung</h2>
            <ul class="inlinemenu">
                <li><a href="/admin/users/">Benutzerkonten</a></li>
                <li><a href="/admin/definitions/">Definitionen</a></li>
                <li><a href="/admin/stats/">Statistiken</a></li>
                <li><a href="/admin/settings/">Einstellungen</a></li>
            </ul>
        </div>
    </div>
</div>
