<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminListsModule */
    use Ubergeek\NanoCm\StatusCode;
?>
<script type="text/javascript" src="ncm/js/ListItems.js"></script>
<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">
        <h1>Listen verwalten</h1>
        <input type="hidden" id="input_list_id" value="<?php echo intval($this->list->id); ?>">

        <div class="toolbar">
            <span class="left">
                <a id="button_back" class="button" href="javascript:void(0);" role="button" title="Zur&uuml;ck zur Listen-&Uuml;bersicht">
                    <img src="ncm/img/fatcow/16/arrow_left.png" alt="" width="16" height="16">Zur&uuml;ck
                </a>
                <a id="button_add" class="button" href="javascript:void(0);" role="button" title="Eintrag hinzuf&uuml;gen">
                    <img src="ncm/img/fatcow/16/add.png" alt="" width="16" height="16">Neu
                </a>
                <a id="button_unlock" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Eintrag freischalten">
                    <img src="ncm/img/fatcow/16/accept_button.png" alt="" width="16" height="16">Entsperren
                </a>
                <a id="button_lock" class="button" href="javascript:void(0)" role="button" title="Ausgew&auml;hlten Eintrag sperren">
                    <img src="ncm/img/fatcow/16/lock.png" alt="" width="16" height="16">Sperren
                </a>
                <a id="button_delete" class="button button-secondary" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Eintrag l&ouml;schen">
                    <img src="ncm/img/fatcow/16/delete.png" alt="" width="16" height="16">L&ouml;schen
                </a>
            </span>
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="ncm/img/spin.gif">

                <label for="input_searchTerm">Suche</label>
                <input id="input_searchTerm" type="text" autofocus="autofocus" value="<?php echo $this->htmlEncode($this->searchTerm); ?>" />

                <label for="select_searchStatusCode" class="spaceleft">Status</label>
                <select id="select_searchStatusCode">
                    <option value="">- Alle -</option>
                    <?php foreach ($this->availableStatusCodes as $code) : ?>
                        <option value="<?php echo $code; ?>" <?php if ($this->searchStatusCode != '' && $this->searchStatusCode == $code) echo ' selected="selected"'; ?>><?php echo StatusCode::convertStatusId($code); ?></option>
                    <?php endforeach; ?>
                </select>

                <a id="button_refresh" class="button spaceleft" role="button" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        </div>

        <div class="editform">
            <div class="row">
                <input class="big" type="text" id="input_list_title" placeholder="Listentitel" value="<?php echo $this->htmlEncode($this->list->title); ?>" autofocus="autofocus" tabindex="0" />
            </div>
        </div>

        <div id="placeholder_listitems" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        module = new ListItems();
    });
</script>