<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminCommentsModule */
    use Ubergeek\NanoCm\StatusCode;
?>
<div class="container">
    <form onsubmit="module.refresh(); return false;">
        <h1>Kommentare</h1>

        <div class="toolbar">
            <span class="left">
                <!--
                <a id="button_add" class="button" href="/admin/comments/edit/" role="button" title="Kommentar hinzuf&uuml;gen">
                    <img src="/ncm/img/fatcow/16/comment_add.png" alt="" width="16" height="16">Neu
                </a>
                -->
                <a id="button_edit" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar bearbeiten">
                    <img src="/ncm/img/fatcow/16/comment_edit.png" alt="" width="16" height="16">Bearbeiten
                </a>
                <a id="button_unlock" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar freigeben">
                    <img src="/ncm/img/fatcow/16/accept_button.png" alt="" width="16" height="16">Freigeben
                </a>
                <a id="button_lock" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar sperren">
                    <img src="/ncm/img/fatcow/16/lock.png" alt="" width="16" height="16">Sperren
                </a>
                <!--
                <a id="button_junk" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar als Junk markieren">
                    <img src="/ncm/img/fatcow/16/bin_empty.png" alt="" width="16" height="16">Junk
                </a>
                -->
                <a id="button_delete" class="button button-secondary" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar l&ouml;schen">
                    <img src="/ncm/img/fatcow/16/comment_delete.png" alt="" width="16" height="16">L&ouml;schen
                </a>
            </span>
            <span class="right" style="float: right; vertical-align: middle">
                <img class="spinner" id="toolbar_spinner" src="/ncm/img/spin.gif">

                <label for="input_searchTerm">Suche</label>
                <input id="input_searchTerm" type="text" autofocus="autofocus" value="<?php echo $this->htmlEncode($this->searchTerm); ?>" />

                <label for="select_searchStatusCode" class="spaceleft">Status</label>
                <select id="select_searchStatusCode">
                    <option value="">- Alle -</option>
                    <?php foreach ($this->availableStatusCodes as $code) : ?>
                        <option value="<?php echo $code; ?>" <?php if ($this->searchStatusCode != '' && $this->searchStatusCode == $code) echo ' selected="selected"'; ?>><?php echo StatusCode::convertStatusId($code); ?></option>
                    <?php endforeach; ?>
                </select>

                <a class="button spaceleft" role="button" id="button_refresh" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img src="/ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16" />Aktualisieren
                </a>
            </span>
        </div>

        <div id="placeholder_comments" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>
<script type="text/javascript">
    function Comments() {
        let app = this;

        /**
         * Initialisiert EventHandler etc.
         */
        app.init = function() {
            app.refresh();
        };

        app.refresh = function(page) {
            ncm.showDefaultLoadingIndicator();
            if (typeof page === 'undefined') page = 1;

            $.ajax('/admin/comments/html/list', {
                cache:      false,
                type:       'GET',
                dataType:   'HTML',
                data:       {
                    searchTerm:         $('#input_searchTerm').val(),
                    searchStatusCode:   $('#select_searchStatusCode').val(),
                    searchPage:         page
                }
            }).done(function(data) {
                $('#placeholder_comments .content').html(data);
                $('.selectall').click(function() {
                    ncm.toggleAllRowsSelection(this);
                });
            }).always(function() {
                ncm.hideDefaultLoadingIndicator();
                $('#input_searchTerm').focus();
            });
        };

        app.init();
    }

    $(document).ready(function() {
        module = new Comments();
    });
</script>