<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminMediaModule */
    use Ubergeek\NanoCm\StatusCode;
?>
<?php if ($this->currentFolder instanceof \Ubergeek\NanoCm\Medium) : ?>
    <h2><?php echo $this->htmlEncode($this->currentFolder->filename); ?></h2>
<?php else : ?>
    <h2>Startseite</h2>
<?php endif; ?>
<table class="list">
    <thead>
        <tr>
            <th style="text-align: center" width="30"><input type="checkbox" class="selectall" /></th>
            <th class="textright" style="width: 30px">ID</th>
            <th>Dateiname</th>
            <th>Titel</th>
            <th class="textright">Gr&ouml;&szlig;e</th>
            <th>Mime-Type</th>
            <th class="textright">&Auml;nderungsdatum</th>
            <th class="textcenter">A</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($this->searchParentId != 0) : ?>
            <tr>
                <td style="padding: 0.5em"></td>
                <td colspan="8" style="padding: 0.5em">
                    <a href="javascript:void(0);" onclick="module.refresh(null, 0);">Startseite</a>
                    <?php foreach ($this->parentFolders as $parentFolder) : ?>
                        /
                        <a href="javascript:void(0);" onclick="module.refresh(null, <?php echo intval($parentFolder->id); ?>)"><?php echo $this->htmlEncode($parentFolder->filename); ?></a>
                    <?php endforeach; ?>
                </td>
            </tr>
        <?php endif; ?>

        <?php if (is_array($this->media) && count($this->media) > 0) : ?>
            <?php foreach ($this->media as $medium) : ?>
                <tr>
                    <td style="text-align: center">
                        <input type="checkbox" class="selection" value="<?php echo $medium->id; ?>" style="text-align: center">
                    </td>
                    <td class="textright pre">
                        <?php if ($medium->entrytype == \Ubergeek\NanoCm\Medium::TYPE_FOLDER) : ?>
                            <a href="javascript:void(0);" onclick="module.editFolder(<?php echo $medium->id; ?>);"><?php echo $medium->id; ?></a>
                        <?php else : ?>
                            <a href="javascript:void(0);" onclick="module.editMedium(<?php echo $medium->id; ?>);"><?php echo $medium->id; ?></a>
                        <?php endif; ?>
                    </td>
                    <td nowrap="nowrap">
                        <?php if ($medium->entrytype == \Ubergeek\NanoCm\Medium::TYPE_FOLDER) : ?>
                            <a href="javascript:void(0);" onclick="module.refresh(null, <?php echo intval($medium->id); ?>)">
                                <img src="/ncm/img/fatcow/16/folder.png" width="16" height="16" alt="Folder" style="vertical-align: middle; margin-right: 0.25em"><?php echo $this->htmlEncode($medium->filename); ?>
                            </a>
                        <?php else : ?>
                            <a href="javascript:void(0);" onclick="module.editMedium(<?php echo $medium->id; ?>);">
                                <img src="/ncm/img/fatcow/16/<?php echo $this->getFileIcon($medium->extension); ?>" width="16" height="16" alt="" style="vertical-align: middle; margin-right: 0.25em"><?php echo $this->htmlEncode($medium->filename); ?>
                            </a>
                        <?php endif; ?>
                    </td>

                    <td><?php echo $this->htmlEncode($medium->title); ?></td>
                    <td class="textright pre" nowrap="nowrap">
                        <?php if ($medium->entrytype == \Ubergeek\NanoCm\Medium::TYPE_FILE) : ?>
                            <?php echo \Ubergeek\NanoCm\Util::sizeHumanReadable($medium->filesize); ?>
                        <?php endif; ?>
                    </td>
                    <td><?php echo $this->htmlEncode($medium->type); ?></td>
                    <td class="textright pre">
                        <?php if ($medium->modification_timestamp instanceof \DateTime) : ?>
                            <?php echo $medium->modification_timestamp->format('Y-m-d H:i'); ?>
                        <?php endif; ?>
                    </td>
                    <td class="textcenter">
                        <?php if ($medium->entrytype == \Ubergeek\NanoCm\Medium::TYPE_FOLDER) : ?>
                            <a href="javascript:void(0);" onclick="module.editFolder(<?php echo $medium->id; ?>);"><img src="/ncm/img/fatcow/16/edit_button.png" alt="Bearbeiten" title="Ordner bearbeiten" width="16" height="16"></a>
                        <?php else : ?>
                            <a href="/admin/media/download/<?php echo $medium->id; ?>"><img src="/ncm/img/fatcow/16/download.png" alt="Download" title="Datei herunterladen" width="16" height="16"></a>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if ($medium->entrytype != \Ubergeek\NanoCm\Medium::TYPE_FOLDER) : ?>
                            <?php echo $this->htmlEncode(StatusCode::convertStatusId($medium->status_code)); ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else : ?>
            <tr class="noresult">
                <td colspan="9">Keine Eintr&auml;ge gefunden</td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>
