<?php /* @var $this \Ubergeek\NanoCm\Module\AdminDashboardModule */

use Ubergeek\NanoCm\Setting; ?>
<div class="container spacing">
    <h1>&Uuml;bersicht</h1>
</div>
<div class="container">
    <div class="column-4 spacing">
        <table class="list" style="margin-top: 0">
            <tr>
                <th colspan="2">Grunddaten Website</th>
            </tr>
            <tr>
                <td>Name der Site</td>
                <td><?php echo $this->htmlEncode($this->getSiteTitle()); ?></td>
            </tr>
            <tr>
                <td>Sprache der Site</td>
                <td><?php echo $this->htmlEncode($this->orm->getSettingValue(Setting::SETTING_SYSTEM_LANG)); ?></td>
            </tr>
            <tr>
                <td>Template</td>
                <td><?php echo $this->htmlEncode($this->orm->getSettingValue(Setting::SETTING_SYSTEM_TEMPLATE_PATH)); ?></td>
            </tr>
            <tr>
                <td>Webmaster-Name</td>
                <td><?php echo $this->htmlEncode($this->orm->getSettingValue(Setting::SETTING_SYSTEM_WEBMASTER_NAME)); ?></td>
            </tr>
            <tr>
                <td>Webmaster-Mail</td>
                <td><?php echo $this->htmlEncode($this->orm->getSettingValue(Setting::SETTING_SYSTEM_WEBMASTER_EMAIL)); ?></td>
            </tr>
        </table>
    </div>
    <div class="column-4 spacing">
        <table class="list" style="margin-top: 0">
            <tr>
                <th colspan="2">Kennzahlen</th>
            </tr>
            <tr>
                <td>Anzahl freigeschalteter Artikel</td>
                <td class="textright pre"><?php echo $this->formatInt($this->numberOfReleasedArticles); ?></td>
            </tr>
            <tr>
                <td>Anzahl freigeschalteter Kommentare</td>
                <td class="textright pre"><?php echo $this->formatInt($this->numberOfActiveComments); ?></td>
            </tr>
            <tr>
                <td>Anzahl nicht freigeschalteter Kommentare</td>
                <td class="textright pre"><?php echo $this->formatInt($this->numberOfInactiveComments); ?></td>
            </tr>
            <tr>
                <td>Zu moderierende Kommentare</td>
                <td class="textright pre"><?php echo $this->formatInt($this->numberOfUnmoderatedComments); ?></td>
            </tr>
            <tr>
                <td>Anzahl Mediendateien</td>
                <td class="textright pre">0</td>
            </tr>
        </table>
    </div>
    <div class="column-4 spacing">
        <div>
            <a class="button" href="/admin/articles/edit/" role="button" title="Neuen Artikel schreiben" style="width: 50%">
                <img src="/ncm/img/fatcow/16/page_add.png" alt="" width="16" height="16">Neuen Artikel schreiben
            </a>
        </div>
        <div style="margin-top: 0.5em"></div>
            <a class="button" href="/admin/comments/?searchStatusCode=<?php echo \Ubergeek\NanoCm\StatusCode::MODERATION_REQUIRED; ?>" role="button" title="Kommentare moderieren" style="width: 50%">
                <img src="/ncm/img/fatcow/16/accept_button.png" alt="" width="16" height="16">Kommentare moderieren
                <?php if ($this->numberOfUnmoderatedComments > 0) : ?>
                    <span class="badge"><?php echo $this->numberOfUnmoderatedComments; ?></span>
                <?php endif; ?>
            </a>
        </div>
    </div>
</div>
