<?php /* @var $this \Ubergeek\NanoCm\Module\AdminStatsModule */ ?>
<script type="text/javascript" src="ncm/js/AccessLog.js"></script>
<input type="hidden" id="input_searchPage" name="searchPage" value="<?php echo (int)$this->searchPage; ?>" />

<?php if (!$this->statsEnabled) : ?>
    <div class="container spacing">
        <div class="msgnote">
            <em>Hinweis:</em> Das F&uuml;hren von Zugriffsstatistiken ist aktuell ausgeschaltet.<br>
            Aktivieren Sie diese Funktion in den <a href="admin/settings/?searchTerm=system.stats">Einstellungen</a>.
        </div>
    </div>
<?php endif; ?>

<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">
        <div class="toolbar">
            <span class="left">
                <a class="button" href="admin/stats/" role="button" title="Zusammengefasste Statistiken anzeigen">
                    <img src="ncm/img/fatcow/16/summary_table.png" alt="" width="16" height="16">&Uuml;bersicht
                </a>
                <a class="button" href="admin/stats/accesslog" role="button" title="Ausf&uuml;hrliches Protokoll der Seitenzugriffe abrufen">
                    <img src="ncm/img/fatcow/16/directory_listing.png" alt="" width="16" height="16">Seitenzugriffe
                </a>
                <a class="button" href="admin/stats/archive" role="button" title="Archiv">
                    <img src="ncm/img/fatcow/16/package.png" alt="" width="16" height="16">Archiv
                </a>
            </span>
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="ncm/img/spin.gif" />

                <label for="inputsearchYear">Jahr</label>
                <input id="input_searchYear" style="width: 80px" type="text" value="<?php echo $this->htmlEncode($this->searchYear); ?>" />

                <label for="select_searchMonth" class="spaceleft">Monat</label>
                <select id="select_searchMonth">
                    <?php for ($i = 1; $i <= 12; $i++) : ?>
                        <option value="<?php echo $i; ?>" <?php if ($this->searchMonth == $i) echo 'selected="selected"'; ?>>
                            <?php echo DateTime::createFromFormat('!m', $i)->format('F'); ?>
                        </option>
                    <?php endfor; ?>
                </select>

                <a id="button_refresh" class="button spaceleft" role="button" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        </div>

        <div id="placeholder_accesslog" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        module = new AccessLog();
    });
</script>