<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminCommentsModule */
    use Ubergeek\NanoCm\StatusCode;
?>
<script type="text/javascript" src="ncm/js/Comments.js"></script>
<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">
        <div class="toolbar">
            <span class="left">
                <a id="button_edit" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar bearbeiten">
                    <img src="ncm/img/fatcow/16/comment_edit.png" alt="" width="16" height="16">Bearbeiten
                </a>
                <a id="button_unlock" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar freigeben">
                    <img src="ncm/img/fatcow/16/accept_button.png" alt="" width="16" height="16">Freigeben
                </a>
                <a id="button_lock" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar sperren">
                    <img src="ncm/img/fatcow/16/lock.png" alt="" width="16" height="16">Sperren
                </a>
                <a id="button_delete" class="button button-secondary" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar l&ouml;schen">
                    <img src="ncm/img/fatcow/16/comment_delete.png" alt="" width="16" height="16">L&ouml;schen
                </a>
            </span>
            <span class="right" style="float: right; vertical-align: middle">
                <img class="spinner" id="toolbar_spinner" src="ncm/img/spin.gif">

                <label for="input_searchTerm">Suche</label>
                <input id="input_searchTerm" type="text" autofocus="autofocus" value="<?php echo $this->htmlEncode($this->searchTerm); ?>" />

                <label for="select_searchStatusCode" class="spaceleft">Status</label>
                <select id="select_searchStatusCode">
                    <option value="">- Alle -</option>
                    <?php foreach ($this->availableStatusCodes as $code) : ?>
                        <option value="<?php echo $code; ?>" <?php if ($this->searchStatusCode != '' && $this->searchStatusCode == $code) echo ' selected="selected"'; ?>><?php echo StatusCode::convertStatusId($code); ?></option>
                    <?php endforeach; ?>
                </select>

                <a class="button spaceleft" role="button" id="button_refresh" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        </div>

        <div id="placeholder_comments" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        module = new Comments();
    });
</script>