<?php
/**
 * NanoCM
 * Copyright (C) 2017 - 2018 André Gewert <agewert@ubergeek.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

/* @var $this \Ubergeek\NanoCm\Module\AdminCommentsModule */
use Ubergeek\NanoCm\StatusCode;
?>
    <table class="list">
        <thead>
        <tr>
            <th style="text-align: center" width="30"><input type="checkbox" class="selectall" /></th>
            <th>Datum</th>
            <th>Kommentar</th>
            <th>Name</th>
            <th>E-Mail</th>
            <th>Artikel</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        <?php if (is_array($this->comments) && count($this->comments) > 0) : ?>
            <?php foreach ($this->comments as $comment) : ?>
                <tr>
                    <td style="text-align: center">
                        <input type="checkbox" class="selection" value="<?php echo $comment->id; ?>" style="text-align: center">
                    </td>
                    <td><?php echo $comment->creation_timestamp->format('Y-m-d H:i'); ?></td>
                    <td>
                        <?php echo $this->htmlEncode($comment->headline); ?><br>
                        <?php echo nl2br($this->htmlEncode($comment->content)); ?>
                    </td>
                    <td><?php echo $this->htmlEncode($comment->username); ?></td>
                    <td><?php echo $this->htmlEncode($comment->email); ?></td>
                    <td><?php echo $this->htmlEncode($this->orm->getArticleHeadlineById($comment->article_id)); ?></td>
                    <td><?php echo $this->htmlEncode(StatusCode::convertStatusId($comment->status_code)); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else : ?>
            <tr>
                <td colspan="7">Keine Kommentare gefunden</td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
<?php $this->includeUserTemplate('blocks/list-paging.phtml'); ?>