<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminMediaModule */
    use Ubergeek\NanoCm\StatusCode;
?>
<script type="text/javascript" src="ncm/js/Media.js"></script>
<div class="container spacing">
    <h1>Medien verwalten</h1>
</div>

<?php if (!$this->isMediaDirWritable) : ?>
    <div class="container spacing">
        <div class="msgnote">
            <em>Hinweis:</em> Das Verzeichnis f&uuml;r die Ablage von Mediendateien ist nicht durch den
                Webserver schreibbar.<br>
                Bitte &uuml;berpr&uuml;fen Sie die Server-Einstellungen bzw. Zugriffsrechte!.
        </div>
    </div>
<?php endif; ?>

<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">
        <input type="hidden" id="input_searchPage" name="searchPage" value="<?php echo (int)$this->searchPage; ?>" />
        <input type="hidden" id="input_searchParentId" name="searchParentId" value="<?php echo (int)$this->searchParentId; ?>" />
        <div class="toolbar">
            <span class="left">
                <a id="button_addfolder" class="button" href="javascript:void(0);" role="button" title="Neuen Ordner erstellen">
                    <img src="ncm/img/fatcow/16/folder_add.png" alt="" width="16" height="16">Neu
                </a>
                <a id="button_unlock" class="button" href="javascript:void(0)" role="button" title="Ausgew&auml;hltes Medium freischalten">
                    <img src="ncm/img/fatcow/16/accept_button.png" alt="" width="16" height="16">Freischalten
                </a>
                <a id="button_lock" class="button" href="javascript:void(0)" role="button" title="Ausgew&auml;hltes Medium sperren">
                    <img src="ncm/img/fatcow/16/lock.png" alt="" width="16" height="16">Sperren
                </a>
                <a id="button_formats" class="button" href="admin/media/formats/" role="button" title="Bildformate verwalten">
                    <img src="ncm/img/fatcow/16/images.png" alt="" width="16" height="16">Formate
                </a>
                <a id="button_delete" class="button button-secondary" href="javascript:void(0);" role="button" title="Ausgew&auml;hltes Medium l&ouml;schen">
                    <img src="ncm/img/fatcow/16/delete.png" alt="" width="16" height="16">L&ouml;schen
                </a>
            </span>
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="ncm/img/spin.gif" />

                <label for="input_searchTerm">Suche</label>
                <input id="input_searchTerm" type="text" autofocus="autofocus" value="<?php echo $this->htmlEncode($this->searchTerm); ?>" />

                <label for="select_searchStatusCode" class="spaceleft">Status</label>
                <select id="select_searchStatusCode">
                    <option value="">- Alle -</option>
                    <?php foreach ($this->availableStatusCodes as $code) : ?>
                        <option value="<?php echo $code; ?>" <?php if ($this->searchStatusCode != '' && $this->searchStatusCode == $code) echo ' selected="selected"'; ?>><?php echo StatusCode::convertStatusId($code); ?></option>
                    <?php endforeach; ?>
                </select>

                <a id="button_refresh" class="button spaceleft" role="button" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        </div>

        <div id="media_dropzone" class="dropzone">
            Dateien zum Hinzuf&uuml;gen hier ablegen
        </div>

        <div id="placeholder_media" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        module = new Media();
    });
</script>