<?php
/* @var $this \Ubergeek\NanoCm\Module\SetupModule */
?>
<h1>
    <img src="ncm/img/nanocm-logo.png" alt="NanoCM" title="NanoCM" width="120">
</h1>

<h2>Einrichtung abgeschlossen</h2>

<div class="label">
    <p>Die Ersteinrichtung von nanoCM wurde abgeschlossen!</p>

    <p>Laden Sie die Seite neu oder klicken Sie auf <a href="<?php echo $this->getRelativeUrl('/'); ?>">diesen Link</a>, um die Seite neu zu laden.
        Wenn alles funktioniert, klicken Sie dort auf &bdquo;Anmelden&ldquo; und geben Sie die eben vergebenen
        Anmeldedaten ein, um sich anzumelden und anschlie&szlig;end den Verwaltungsbereich aufzurufen.
    </p>
</div>
