<?php /* @var $this \Ubergeek\NanoCm\Module\AdminMediaModule */ ?>
<script type="text/javascript" src="ncm/js/MediaFormats.js"></script>
<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">

        <div class="toolbar">
            <span class="left">
                <a id="button_add" class="button" href="javascript:void(0);" role="button" title="Neuen Bildformat anlegen">
                    <img src="ncm/img/fatcow/16/add.png" alt="" width="16" height="16">Neu
                </a>
                <a id="button_edit" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hltes Bildformat bearbeiten">
                    <img src="ncm/img/fatcow/16/edit_button.png" alt="" width="16" height="16">Bearbeiten
                </a>
                <a id="button_formats" class="button" href="admin/media/" role="button" title="Mediendateien verwalten">
                    <img src="ncm/img/fatcow/16/folder_image.png" alt="" width="16" height="16">Dateien
                </a>
                <a id="button_delete" class="button button-secondary" href="javascript:void(0);" role="button" title="Ausgew&auml;hltes Bildformat l&ouml;schen">
                    <img src="ncm/img/fatcow/16/delete.png" alt="" width="16" height="16">L&ouml;schen
                </a>
            </span>
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="ncm/img/spin.gif" />
                <a id="button_refresh" class="button spaceleft" role="button" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        </div>

        <div id="placeholder_formats" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        module = new MediaFormats();
    });
</script>