<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminListsModule */
    use Ubergeek\NanoCm\StatusCode;
?>
<table class="list">
    <thead>
    <tr>
        <th style="text-align: center" width="30"><input type="checkbox" class="selectall" /></th>
        <th>Titel</th>
        <th>Inhalt</th>
        <th>Parameter</th>
        <th>Sortiercode</th>
        <th>Status</th>
    </tr>
    </thead>
    <tbody>
    <?php if (is_array($this->listItems) && count($this->listItems) > 0) : ?>
        <?php foreach ($this->listItems as $item) : ?>
            <tr>
                <td style="text-align: center">
                    <input type="checkbox" class="selection" value="<?php echo $item->id; ?>" style="text-align: center">
                </td>
                <td><a href="javascript:void(0);" onclick="module.editClickedListItem(this);" data-id="<?php echo intval($item->id); ?>"><?php echo $this->htmlEncode($item->title); ?></a></td>
                <td><?php echo $this->htmlEncode($item->content); ?></td>
                <td><?php echo $this->htmlEncode($item->parameters); ?></td>
                <td><?php echo $this->htmlEncode($item->sorting_code); ?></td>
                <td><?php echo $this->htmlEncode(StatusCode::convertStatusId($item->status_code)); ?></td>
            </tr>
        <?php endforeach; ?>
    <?php else : ?>
        <tr class="noresult">
            <td colspan="6">Keine Eintr&auml;ge gefunden</td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>
