<?php
/* @var $this \Ubergeek\NanoCm\Module\AdminMediaModule */
use Ubergeek\NanoCm\StatusCode;
?>
<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">
        <h1>Medien verwalten</h1>
        <input type="hidden" id="input_searchPage" name="searchPage" value="<?php echo intval($this->searchPage); ?>" />
        <input type="hidden" id="input_searchParentId" name="searchParentId" value="<?php echo intval($this->searchParentId); ?>" />

        <div class="toolbar">
            <span class="left">
                <a id="button_add" class="button" href="javascript:void(0);" role="button" title="Medium hinzuf&uuml;gen">
                    <img src="/ncm/img/fatcow/16/add.png" alt="" width="16" height="16">Neu
                </a>
                <a id="button_addfolder" class="button" href="javascript:void(0);" role="button" title="Neuen Ordner erstellen">
                    <img src="/ncm/img/fatcow/16/folder_add.png" alt="" width="16" height="16">Neuer Ordner
                </a>
                <!--
                <a id="button_edit" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hltes Medium bearbeiten">
                    <img src="/ncm/img/fatcow/16/edit_button.png" alt="" width="16" height="16">Bearbeiten
                </a>
                -->
                <a id="button_unlock" class="button" href="javascript:void(0)" role="button" title="Ausgew&auml;hltes Medium freischalten">
                    <img src="/ncm/img/fatcow/16/accept_button.png" alt="" width="16" height="16">Freischalten
                </a>
                <a id="button_lock" class="button" href="javascript:void(0)" role="button" title="Ausgew&auml;hltes Medium sperren">
                    <img src="/ncm/img/fatcow/16/lock.png" alt="" width="16" height="16">Sperren
                </a>
                <a id="button_delete" class="button button-secondary" href="javascript:void(0);" role="button" title="Ausgew&auml;hltes Medium l&ouml;schen">
                    <img src="/ncm/img/fatcow/16/delete.png" alt="" width="16" height="16">L&ouml;schen
                </a>
            </span>
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="/ncm/img/spin.gif" />

                <label for="input_searchTerm">Suche</label>
                <input id="input_searchTerm" type="text" autofocus="autofocus" value="<?php echo $this->htmlEncode($this->searchTerm); ?>" />

                <label for="select_searchStatusCode" class="spaceleft">Status</label>
                <select id="select_searchStatusCode">
                    <option value="">- Alle -</option>
                    <?php foreach ($this->availableStatusCodes as $code) : ?>
                        <option value="<?php echo $code; ?>" <?php if ($this->searchStatusCode != '' && $this->searchStatusCode == $code) echo ' selected="selected"'; ?>><?php echo StatusCode::convertStatusId($code); ?></option>
                    <?php endforeach; ?>
                </select>

                <a id="button_refresh" class="button spaceleft" role="button" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="/ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        </div>

        <div id="media_dropzone" style="border: solid silver 2px; padding: 2em">
            Dateien hier ablegen
        </div>

        <div id="placeholder_media" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    function Media() {
        let app = this;
        app.page = $('#input_searchPage').val();
        app.parentId = $('#input_searchParentId').val();

        /**
         * Initialisiert Event-Handler etc.
         */
        app.init = function() {

            var dropZone = document.getElementById('media_dropzone');

            dropZone.addEventListener('dragover', function(evt) {
                console.log('dragover');
                evt.stopPropagation();
                evt.preventDefault();
                evt.dataTransfer.dropEffect = 'copy';
            }, false);

            dropZone.addEventListener('drop', function(evt) {
                console.log('drop');
                evt.stopPropagation();
                evt.preventDefault();

                var files = evt.dataTransfer.files;
                console.log(files);

                if (files.length > 0) {
                    var reader = new FileReader();
                    var senddata = new Object();

                    senddata.name = files[0].name;
                    senddata.date = files[0].lastModified;
                    senddata.size = files[0].size;
                    senddata.type = files[0].type;

                    reader.onload = function (fileData) {
                        senddata.fileData = fileData.target.result;
                        ncm.showDefaultLoadingIndicator();

                        $.ajax('/admin/media/upload', {
                            cache:      false,
                            type:       'POST',
                            dataType:   'JSON',
                            data:       {
                                file:   senddata
                            }
                        }).done(function(data) {
                            //console.log(data);
                        }).always(function() {
                            ncm.hideDefaultLoadingIndicator();
                            app.refresh();
                        });
                    };

                    //reader.readAsDataURL(files[0]);
                    reader.readAsBinaryString(files[0]);
                }
            }, false);

            $('#button_edit').click(function() {

            });

            $('#button_addfolder').click(function() {
                app.addFolder();
            });

            $('#button_unlock').click(function() {
                app.unlockSelected();
            });

            $('#button_lock').click(function() {
                app.lockSelected();
            });

            $('#button_delete').click(function() {
                app.deleteSelected();
            });

            app.refresh();
        };

        /**
         * Aktualisiert die Liste der Pages
         *
         * @param {int} page Anzuzeigende Seite
         * @param {int} parentId Übergeordneter Ordner
         */
        app.refresh = function(page, parentId) {
            ncm.showDefaultLoadingIndicator();
            if (typeof page === 'undefined' || page === null) page = app.page;
            if (typeof parentId === 'undefined' || parentId === null) parentId = app.parentId;

            $.ajax('/admin/media/html/list', {
                cache:      false,
                type:       'GET',
                dataType:   'HTML',
                data: {
                    searchTerm:         $('#input_searchTerm').val(),
                    searchStatusCode:   $('#select_searchStatusCode').val(),
                    searchPage:         page,
                    searchParentId:     parentId
                }
            }).done(function(data) {
                $('#placeholder_media .content').html(data);
                $('.selectall').click(function() {
                    ncm.toggleAllRowsSelection(this);
                });
            }).always(function() {
                ncm.hideDefaultLoadingIndicator();
                $('#input_searchTerm').focus();
            });
        };

        app.editClickedMedium = function(clickedElement) {
            // TODO implementieren
            let id = $(clickedElement).attr('data-id');
            console.log(id);
        };

        /**
         * Löscht die ausgewählten Mediendateien
         */
        app.deleteSelected = function() {
            let ids = ncm.getSelectedRowIds();
            if (ids.length > 0) {
                if (confirm('Wollen Sie die ausgewählten Mediendateien wirklich löschen?')) {
                    ncm.showDefaultLoadingIndicator();
                    $.ajax('/admin/media/ajax/delete', {
                        cache:      false,
                        type:       'GET',
                        dataType:   'JSON',
                        data: {
                            ids:    ids
                        }
                    }).always(function () {
                        ncm.hideDefaultLoadingIndicator();
                        app.refresh();
                    });
                }
            }
        };

        /**
         * Sperrt die ausgewählten Mediendateien
         */
        app.lockSelected = function() {
            let ids = ncm.getSelectedRowIds();
            if (ids.length > 0) {
                ncm.showDefaultLoadingIndicator();
                $.ajax('/admin/media/ajax/lock', {
                    cache:      false,
                    type:       'GET',
                    dataType:   'JSON',
                    data: {
                        ids:    ids
                    }
                }).always(function () {
                    ncm.hideDefaultLoadingIndicator();
                    app.refresh();
                });
            }
        };

        /**
         * Entsperrt die ausgewählten Mediendateien
         */
        app.unlockSelected = function() {
            let ids = ncm.getSelectedRowIds();
            if (ids.length > 0) {
                ncm.showDefaultLoadingIndicator();
                $.ajax('/admin/media/ajax/unlock', {
                    cache:      false,
                    type:       'GET',
                    dataType:   'JSON',
                    data: {
                        ids:    ids
                    }
                }).always(function () {
                    ncm.hideDefaultLoadingIndicator();
                    app.refresh();
                });
            }
        };

        app.addFolder = function() {
            console.log("Add a folder");
        };

        app.init();
    }

    $(document).ready(function() {
        module = new Media();
    });
</script>