<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminArticleseriesModule */
    use Ubergeek\NanoCm\StatusCode;
?>
<?php if ($this->articleseries->id != null) : ?>
    <div class="row">
        <label for="edit_articleseries_creation_timestamp">Erstellungsdatum</label>
        <input type="text" id="edit_articleseries_creation_timestamp" readonly="readonly" value="<?php echo $this->articleseries->creation_timestamp->format('Y-m-d H:i'); ?>">
    </div>
    <div class="row">
        <label for="edit_articleseries_modification_timestamp">Letzte &Auml;nderung</label>
        <input type="text" id="edit_articleseries_modification_timestamp" readonly="readonly" value="<?php echo $this->articleseries->modification_timestamp->format('Y-m-d H:i'); ?>">
    </div>
<?php endif; ?>
<div class="row">
    <label for="edit_articleseries_title">Titel</label>
    <input type="text" class="autofocus" id="edit_articleseries_title" value="<?php echo $this->htmlEncode($this->articleseries->title); ?>">
</div>
<div class="row">
    <label for="edit_articleseries_description">Beschreibung</label>
    <input type="text" id="edit_articleseries_description" value="<?php echo $this->htmlEncode($this->articleseries->description); ?>">
</div>
<div class="row">
    <label for="edit_articleseries_sorting_key">Sortierung</label>
    <select id="edit_articleseries_sorting_key" size="1">
        <option value="">- Keine Vorgabe -</option>
        <?php foreach ($this->availableSortingModes as $definition) : ?>
            <option value="<?php echo $this->htmlEncode($definition->key); ?>" <?php if ($this->articleseries->sorting_key == $definition->key) echo 'selected="selected"'; ?>><?php echo $this->htmlEncode($definition->title); ?></option>
        <?php endforeach; ?>
    </select>
</div>
<div class="row">
    <label for="edit_articleseries_status_code">Status</label>
    <select id="edit_articleseries_status_code" size="1">
        <?php foreach ($this->availableStatusCodes as $code) : ?>
            <option value="<?php echo $code; ?>" <?php if ($this->articleseries->status_code == $code) echo ' selected="selected"'; ?>><?php echo StatusCode::convertStatusId($code); ?></option>
        <?php endforeach; ?>
    </select>
</div>