<?php
/* @var $this \Ubergeek\NanoCm\Module\AdminInstallationModule */

use Ubergeek\NanoCm\Util;

?>
    <table class="list">
        <thead>
            <tr>
                <th style="text-align: center" width="30"><input type="checkbox" class="selectall" /></th>
                <th class="px-1">Datum des Backups</th>
                <th class="px-1">Dateiname</th>
                <th class="textright px-1">Dateigr&ouml;&szlig;e</th>
                <th class="textright px-1">nanoCM-Version</th>
            </tr>
        </thead>
        <tbody>
            <?php if (is_array($this->existingBackups) && count($this->existingBackups) > 0) : ?>
                <?php foreach ($this->existingBackups as $backupInfo) : ?>
                    <tr>
                        <td style="text-align: center">
                            <input type="checkbox" class="selection" value="<?php echo basename($backupInfo->filename); ?>" style="text-align: center">
                        </td>
                        <td class="textright pre px-1">
                            <?php if ($backupInfo->creationDateTime instanceof \DateTime) : ?>
                                <?php echo $backupInfo->creationDateTime->format('Y-m-d H:i:s'); ?>
                            <?php else : ?>
                                &mdash;
                            <?php endif; ?>
                        </td>
                        <td class="px-1"><?php echo $this->htmlEncode(basename($backupInfo->filename)); ?></td>
                        <td class="pre textright px-1"><?php echo Util::sizeHumanReadable($backupInfo->filesize); ?></td>
                        <td class="pre textright px-1"><?php echo $this->htmlEncode($backupInfo->version); ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else : ?>
                <tr class="noresult">
                    <td colspan="6">Keine Backups vorhanden</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
<?php $this->includeUserTemplate('blocks/list-paging.phtml'); ?>