<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminCommentsModule */
    use Ubergeek\NanoCm\StatusCode;
    use Ubergeek\NanoCm\Util;
?>
    <table class="list">
        <thead>
        <tr>
            <th style="text-align: center" width="30"><input type="checkbox" class="selectall" /></th>
            <th class="textright">Datum</th>
            <th>Kommentar</th>
            <th>Name</th>
            <th>E-Mail</th>
            <th>Artikel</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        <?php if (is_array($this->comments) && count($this->comments) > 0) : ?>
            <?php foreach ($this->comments as $comment) : ?>
                <tr>
                    <td style="text-align: center">
                        <input type="checkbox" class="selection" value="<?php echo $comment->id; ?>" style="text-align: center">
                    </td>
                    <td class="textright pre"><?php echo $comment->creation_timestamp->format('Y-m-d H:i'); ?></td>
                    <td>
                        <a href="javascript:void(0);" data-id="<?php echo $this->htmlEncode($comment->id); ?>" onclick="module.editClickedComment(this);">
                            <?php if (strlen(trim($comment->headline)) > 0) : ?>
                                <?php echo $this->htmlEncode($comment->headline); ?><br>
                            <?php endif; ?>
                            <?php echo $this->htmlEncode(Util::shortenText($comment->content, 80)); ?>
                        </a>
                    </td>
                    <td><?php echo $this->htmlEncode($comment->username); ?></td>
                    <td><?php echo $this->htmlEncode($comment->email); ?></td>
                    <td><?php echo $this->htmlEncode($this->orm->getArticleHeadlineById($comment->article_id)); ?></td>
                    <td><?php echo $this->htmlEncode(StatusCode::convertStatusId($comment->status_code)); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else : ?>
            <tr class="noresult">
                <td colspan="7">Keine Kommentare gefunden</td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
<?php $this->includeUserTemplate('blocks/list-paging.phtml'); ?>