<?php
/* @var $this AdminMediaModule */
use Ubergeek\NanoCm\Module\AdminMediaModule;
?>
<div class="mx-4 my-2">
    <?php if (count($this->availableContentPlugins) > 0) : ?>
    <ul class="block-selection plugin-selection">
        <?php foreach ($this->availableContentPlugins as $plugin) : ?>
            <li class="plugin-item" data-plugin-id="<?php echo $this->htmlEncode($plugin->getKey()); ?>">
                <p><strong><?php echo $this->htmlEncode($plugin->getName()); ?></strong></p>
                <p><?php echo $this->htmlEncode($plugin->getDescription()); ?></p>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php else : ?>
        <p class="noresult">&ndash;&nbsp;Keine Content-Plugins verf&uuml;gbar&nbsp;&ndash;</p>
    <?php endif; ?>
</div>
