<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminCommentsModule */
    use Ubergeek\NanoCm\StatusCode;
?>
<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">
        <h1>Kommentare verwalten</h1>

        <div class="toolbar">
            <span class="left">
                <a id="button_edit" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar bearbeiten">
                    <img src="ncm/img/fatcow/16/comment_edit.png" alt="" width="16" height="16">Bearbeiten
                </a>
                <a id="button_unlock" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar freigeben">
                    <img src="ncm/img/fatcow/16/accept_button.png" alt="" width="16" height="16">Freigeben
                </a>
                <a id="button_lock" class="button" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar sperren">
                    <img src="ncm/img/fatcow/16/lock.png" alt="" width="16" height="16">Sperren
                </a>
                <a id="button_delete" class="button button-secondary" href="javascript:void(0);" role="button" title="Ausgew&auml;hlten Kommentar l&ouml;schen">
                    <img src="ncm/img/fatcow/16/comment_delete.png" alt="" width="16" height="16">L&ouml;schen
                </a>
            </span>
            <span class="right" style="float: right; vertical-align: middle">
                <img class="spinner" id="toolbar_spinner" src="ncm/img/spin.gif">

                <label for="input_searchTerm">Suche</label>
                <input id="input_searchTerm" type="text" autofocus="autofocus" value="<?php echo $this->htmlEncode($this->searchTerm); ?>" />

                <label for="select_searchStatusCode" class="spaceleft">Status</label>
                <select id="select_searchStatusCode">
                    <option value="">- Alle -</option>
                    <?php foreach ($this->availableStatusCodes as $code) : ?>
                        <option value="<?php echo $code; ?>" <?php if ($this->searchStatusCode != '' && $this->searchStatusCode == $code) echo ' selected="selected"'; ?>><?php echo StatusCode::convertStatusId($code); ?></option>
                    <?php endforeach; ?>
                </select>

                <a class="button spaceleft" role="button" id="button_refresh" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        </div>

        <div id="placeholder_comments" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>
<script type="text/javascript">
    function Comments() {
        let app = this;

        /**
         * Initialisiert EventHandler etc.
         */
        app.init = function() {
            $('#button_refresh').click(function() {
                app.refresh();
            });
            $('#button_lock').click(function() {
                app.lockSelected();
            });
            $('#button_unlock').click(function() {
                app.unlockSelected();
            });
            $('#button_edit').click(function() {
                app.editSelected();
            });
            $('#button_delete').click(function() {
                app.deleteSelected();
            });
            app.refresh();
        };

        /**
         * Aktualisiert die Liste der angezeigten Kommentare
         * @param {int} page Optional: anzuzeigende Seite
         */
        app.refresh = function(page) {
            ncm.showDefaultLoadingIndicator();
            if (typeof page === 'undefined') page = 1;

            $.ajax('admin/comments/html/list', {
                cache:      false,
                type:       'GET',
                dataType:   'HTML',
                data:       {
                    searchTerm:         $('#input_searchTerm').val(),
                    searchStatusCode:   $('#select_searchStatusCode').val(),
                    searchPage:         page
                }
            }).done(function(data) {
                $('#placeholder_comments .content').html(data);
                $('.selectall').click(function() {
                    ncm.toggleAllRowsSelection(this);
                });
            }).always(function() {
                ncm.hideDefaultLoadingIndicator();
                $('#input_searchTerm').focus();
            });
        };

        /**
         * Sperrt die ausgewählten Kommentare
         */
        app.lockSelected = function() {
            let ids = ncm.getSelectedRowIds();
            if (ids.length > 0) {
                ncm.showDefaultLoadingIndicator();
                $.ajax('admin/comments/ajax/lock', {
                    cache:      false,
                    type:       'GET',
                    dataType:   'JSON',
                    data:       {
                        ids:    ids
                    }
                }).always(function() {
                    ncm.hideDefaultLoadingIndicator();
                    app.refresh();
                });
            }
        };

        /**
         * Entsperrt die ausgewählten Kommentare
         */
        app.unlockSelected = function() {
            let ids = ncm.getSelectedRowIds();
            if (ids.length > 0) {
                ncm.showDefaultLoadingIndicator();
                $.ajax('admin/comments/ajax/unlock', {
                    cache:      false,
                    type:       'GET',
                    dataType:   'JSON',
                    data:       {
                        ids:    ids
                    }
                }).always(function() {
                    ncm.hideDefaultLoadingIndicator();
                    app.refresh();
                });
            }
        };

        /**
         * Ruft die Bearbeitungsmaske für den angeklickten Kommentar auf
         * @param {node} clickedLink
         */
        app.editClickedComment = function(clickedLink) {
            let id = $(clickedLink).attr('data-id');
            app.editComment(id);
        };

        /**
         * Ruft die Bearbeitungsmaske für den Kommentar mit der angegebenen ID auf
         * @param {int} id
         */
        app.editComment = function(id) {
            let dlg = new ncm.InlinePopup(
                'admin/comments/html/edit/', {
                    id: id
                }, {
                    headline:   'Kommentar bearbeiten',
                    width:      500,
                    height:     480,
                    loaded:     function() {
                        ncm.focusDefaultElement();
                    }
                }, {
                    cancel: {
                        caption: 'Abbrechen',
                        clicked:  function() {
                            dlg.close();
                        }
                    }, save: {
                        caption: 'Speichern',
                        clicked: function() {
                            ncm.showDefaultLoadingIndicator();
                            $.ajax('admin/comments/ajax/save', {
                                cache:      false,
                                type:       'POST',
                                dataType:   'JSON',
                                data:        {
                                    id:             id,
                                    username:       $('#edit_comment_username').val(),
                                    email:          $('#edit_comment_email').val(),
                                    status_code:    $('#edit_comment_status_code').val(),
                                    use_gravatar:   $('#edit_comment_use_gravatar').prop('checked')? '1' : '0',
                                    headline:       $('#edit_comment_headline').val(),
                                    content:        $('#edit_comment_content').val()
                                }
                            }).always(function() {
                                ncm.hideDefaultLoadingIndicator();
                                dlg.close();
                                app.refresh();
                            });
                        }
                    }
                }
            );
        };

        /**
         * Ruft die Bearbeitungsmaske für den ersten ausgewählten Kommentar auf
         */
        app.editSelected = function() {
            let id = ncm.getFirstSelectedRowId();
            if (id != null) {
                app.editComment(id);
            }
        };

        /**
         * Löscht die ausgewählten Kommentare
         */
        app.deleteSelected = function() {
            let ids = ncm.getSelectedRowIds();
            if (ids.length > 0) {
                if (confirm('Wollen Sie die ausgewählten Einstellungen wirklich endgültig löschen?')) {
                    ncm.showDefaultLoadingIndicator();
                    $.ajax('admin/comments/ajax/delete', {
                        cache:      false,
                        type:       'POST',
                        dataType:   'JSON',
                        data:       {
                            ids:    ids
                        }
                    }).always(function() {
                        ncm.hideDefaultLoadingIndicator();
                        app.refresh();
                    });
                }
            }
        };

        app.init();
    }

    $(document).ready(function() {
        module = new Comments();
    });
</script>