<?php /* @var $this \Ubergeek\NanoCm\Module\AdminStatsModule */ ?>

<h2 class="mt-4">Abgerufene URLs (Top 25)</h2>
<table class="list">
    <thead>
        <tr>
            <th>URL</th>
            <th width="10%" class="textright">Abrufe</th>
            <th width="10%" class="textright">Anteil in %</th>
        </tr>
    </thead>
    <tbody>
        <?php if (is_array($this->statsUrls) && count($this->statsUrls) > 0) : ?>
            <?php
                $sum = 0; $sumPercent = 0;
                foreach ($this->statsUrls as $url) { $sum += $url['sumcount']; }
            ?>
            <?php foreach ($this->statsUrls as $url) : ?>
                <tr>
                    <td><?php echo $this->htmlEncode($url['url']); ?></td>
                    <td class="textright pre"><?php echo $this->formatInt($url['sumcount']); ?></td>
                    <td class="textright pre"><?php echo $this->formatFloat(($url['sumcount'] /$sum) *100); ?></td>
                </tr>
                <?php $sumPercent += ($url['sumcount'] /$sum) *100; ?>
            <?php endforeach; ?>
            <tr>
                <th>Summe</th>
                <th class="textright pre">
                    <?php echo $this->formatInt($sum); ?>
                </th>
                <th class="textright pre">
                    <?php echo $this->formatFloat($sumPercent); ?>
                </th>
            </tr>
        <?php else : ?>
            <tr class="noresult">
                <td colspan="3">
                    &mdash;&nbsp;Keine Ergebnisse&nbsp;&mdash;
                </td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>

<h2 class="mt-4">Browser</h2>
<table class="list">
    <thead>
    <tr>
        <th>Browser</th>
        <th width="10%" class="textright">Abrufe</th>
        <th width="10%" class="textright">Anteil in %</th>
    </tr>
    </thead>
    <tbody>
    <?php if (is_array($this->statsBrowsers) && count($this->statsBrowsers) > 0) : ?>
        <?php
            $sum = 0; $sumPercent = 0;
            foreach ($this->statsBrowsers as $browser) { $sum += $browser['sumcount']; }
        ?>
        <?php foreach ($this->statsBrowsers as $browser) : ?>
            <tr>
                <td><?php echo $this->htmlEncode($browser['browsername']); ?></td>
                <td class="textright pre"><?php echo $this->formatInt($browser['sumcount']); ?></td>
                <td class="textright pre"><?php echo $this->formatFloat(($browser['sumcount'] /$sum) *100); ?></td>
            </tr>
            <?php $sumPercent += ($browser['sumcount'] /$sum) *100; ?>
        <?php endforeach; ?>
        <tr>
            <th>Summe</th>
            <th class="textright pre">
                <?php echo $this->formatInt($sum); ?>
            </th>
            <th class="textright pre">
                <?php echo $this->formatFloat($sumPercent); ?>
            </th>
        </tr>
    <?php else : ?>
        <tr class="noresult">
            <td colspan="3">
                &mdash;&nbsp;Keine Ergebnisse&nbsp;&mdash;
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>

<h2 class="mt-4">Betriebssysteme</h2>
<table class="list">
    <thead>
    <tr>
        <th>Betriebssystem</th>
        <th width="10%" class="textright">Abrufe</th>
        <th width="10%" class="textright">Anteil in %</th>
    </tr>
    </thead>
    <tbody>
    <?php if (is_array($this->statsOses) && count($this->statsOses) > 0) : ?>
        <?php
            $sum = 0; $sumPercent = 0;
            foreach ($this->statsOses as $os) { $sum += $os['sumcount']; }
        ?>
        <?php foreach ($this->statsOses as $os) : ?>
            <tr>
                <td><?php echo $this->htmlEncode($os['osname']); ?></td>
                <td class="textright pre"><?php echo $this->formatInt($os['sumcount']); ?></td>
                <td class="textright pre"><?php echo $this->formatInt((int)($os['sumcount'] /$sum) *100); ?></td>
            </tr>
            <?php $sumPercent += ($os['sumcount'] /$sum) *100; ?>
        <?php endforeach; ?>
        <tr>
            <th>Summe</th>
            <th class="textright pre"><?php echo $this->formatInt($sum); ?></th>
            <th class="textright pre"><?php echo $this->formatFloat($sumPercent); ?></th>
        </tr>
    <?php else : ?>
        <tr class="noresult">
            <td colspan="3">
                &mdash;&nbsp;Keine Ergebnisse&nbsp;&mdash;
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>

<h2 class="mt-4">Herkunftsländer</h2>
<table class="list">
    <thead>
    <tr>
        <th>Land</th>
        <!--<th>Region</th>-->
        <th width="10%" class="textright">Abrufe</th>
        <th width="10%" class="textright">Anteil in %</th>
    </tr>
    </thead>
    <tbody>
    <?php if (is_array($this->statsCountry) && count($this->statsCountry) > 0) : ?>
        <?php
            $sum = 0; $sumPercent = 0;
            foreach ($this->statsCountry as $country) {  $sum += $country['sumcount']; }
        ?>
        <?php foreach ($this->statsCountry as $country) : ?>
            <tr>
                <td><?php echo $this->htmlEncode($country['country']); ?></td>
                <td class="textright pre"><?php echo $this->formatInt($country['sumcount']); ?></td>
                <td class="textright pre"><?php echo $this->formatFloat(($country['sumcount'] /$sum) *100); ?></td>
            </tr>
            <?php $sumPercent += ($country['sumcount'] /$sum) *100; ?>
        <?php endforeach; ?>
        <tr>
            <th>Summe</th>
            <th colspan="1" class="textright pre"><?php echo $this->formatInt($sum); ?></th>
            <th colspan="1" class="textright pre"><?php echo $this->formatFloat($sumPercent); ?></th>
        </tr>
    <?php else : ?>
        <tr class="noresult">
            <td colspan="3">
                &mdash;&nbsp;Keine Ergebnisse&nbsp;&mdash;
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>

<h2 class="mt-4">Sessions</h2>
<table class="list">
    <thead>
    <tr>
        <th>Eindeutige Sessions</th>
        <th width="10%" class="textright">Anzahl</th>
    </tr>
    </thead>
    <tbody>
    <?php if (is_array($this->statsSessionId) && count($this->statsSessionId) > 0) : ?>
        <?php foreach ($this->statsSessionId as $sessionId) : ?>
            <tr>
                <td></td>
                <td class="textright pre"><?php echo $this->formatInt($sessionId['c']); ?></td>
            </tr>
        <?php endforeach; ?>
    <?php else : ?>
        <tr class="noresult">
            <td colspan="3">
                &mdash;&nbsp;Keine Ergebnisse&nbsp;&mdash;
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>