<?php  /* @var $this \Ubergeek\NanoCm\Module\AdminBasicsettingsModule */ ?>
<div class="container spacing">
    <h1>Grundlegende Einstellungen verwalten</h1>

    <form onsubmit="module.refresh(); return false;">
        <div class="toolbar">
            <span class="left">
                <a id="button_extendedsettings" class="button button-secondary" href="admin/settings/" role="button" title="Erweiterte Einstellungen">
                    <img src="ncm/img/fatcow/16/more_form.png" alt="" width="16" height="16">Erweiterte Einstellungen
                </a>
            </span>
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="ncm/img/spin.gif" />

                <a id="button_safe" class="button spaceleft" role="button" title="Einstellungen speichern" href="javascript:void(0)">
                    <img class="imageonly" src="ncm/img/fatcow/16/save_as.png" alt="" width="16" height="16">Speichern
                </a>
            </span>
        </div>

        <fieldset>
            <legend>Seiteninformationen</legend>

            <div class="row">
                <label>Titel der Website</label>
                <input name="pagetitle" data-label="Titel der Website" class="text" type="text" id="input_pagetitle" value="" placeholder="www.example.com" required>
            </div>
            <div class="row">
                <label>Sprache der Website</label>
                <input name="lang" data-label="Sprache der Website" class="text" type="text" id="input_lang" value="de" placeholder="de" required>
            </div>
            <div class="row">
                <label>Vorname(n) des Seitenbetreibers</label>
                <input name="webmaster_firstname" data-label="Vorname(n) des Seitenbetreibers" class="text" type="text" id="input_webmaster_firstname" value="" placeholder="Max" required>
            </div>
            <div class="row">
                <label>Nachname des Seitenbetreibers</label>
                <input name="webmaster_lastname" data-label="Nachname des Seitenbetreibers" class="text" type="text" id="input_webmaster_lastname" value="" placeholder="Mustermann" required>
            </div>
            <div class="row">
                <label>E-Mail-Adresse des Seitenbetreibers</label>
                <input name="webmaster_email" data-label="E-Mail-Adresse des Seitenbetreibers" class="text" type="email" id="input_webmaster_email" value="" placeholder="max.mustermann@example.com" required>
            </div>
        </fieldset>

        <fieldset>
            <legend>Seitenbetreiber</legend>
        </fieldset>

        <fieldset>
            <legend>Kommentare und Trackbacks</legend>
        </fieldset>
    </form>
</div>
