<?php /* @var $this \Ubergeek\NanoCm\Module\AdminStatsModule */ ?>
<script type="text/javascript" src="ncm/js/StatsArchive.js"></script>

<div class="container spacing">
    <h1>Statistiken</h1>
</div>

<?php if (!$this->statsEnabled) : ?>
    <div class="container spacing">
        <div class="msgnote">
            <em>Hinweis:</em> Das F&uuml;hren von Zugriffsstatistiken ist aktuell ausgeschaltet.<br>
            Aktivieren Sie diese Funktion in den <a href="admin/settings/?searchTerm=system.stats">Einstellungen</a>.
        </div>
    </div>
<?php endif; ?>

<div class="container spacing">
    <form onsubmit="module.refresh(); return false;">
        <div class="toolbar">
            <span class="left">
                <a class="button" href="admin/stats/" role="button" title="Zusammengefasste Statistiken anzeigen">
                    <img src="ncm/img/fatcow/16/summary_table.png" alt="" width="16" height="16">&Uuml;bersicht
                </a>
                <a class="button" href="admin/stats/accesslog" role="button" title="Ausf&uuml;hrliches Protokoll der Seitenzugriffe abrufen">
                    <img src="ncm/img/fatcow/16/directory_listing.png" alt="" width="16" height="16">Seitenzugriffe
                </a>
                <a class="button" href="admin/stats/archive" role="button" title="Archiv">
                    <img src="ncm/img/fatcow/16/package.png" alt="" width="16" height="16">Archiv
                </a>

                <a id="button_add" class="button" href="javascript:void(0);" role="button" title="Statistik-Archiv erstellen">
                    <img src="ncm/img/fatcow/16/add_package.png" alt="" width="16" height="16">Archiv erstellen
                </a>
            </span>
            <span class="right" style="float: right">
                <img class="spinner" id="toolbar_spinner" src="ncm/img/spin.gif" />
                <a id="button_refresh" class="button spaceleft" role="button" title="Ansicht aktualisieren" href="javascript:void(0)">
                    <img class="imageonly" src="ncm/img/fatcow/16/arrow_refresh.png" alt="" width="16" height="16">
                </a>
            </span>
        </div>
        <div id="placeholder_statsarchive" class="placeholder">
            <div class="blanker"></div>
            <div class="content"></div>
        </div>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        module = new StatsArchive();
    });
</script>
