<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminArticlesModule */
    use Ubergeek\NanoCm\StatusCode;
?>
<table class="list">
    <thead>
        <tr>
            <th style="text-align: center" width="30"><input type="checkbox" class="selectall" /></th>
            <th>Titel</th>
            <th>Autor</th>
            <th>Startdatum</th>
            <th>Pub.-Datum</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        <?php if (is_array($this->articles) && count($this->articles) > 0) : ?>
            <?php foreach ($this->articles as $article) : ?>
                <tr>
                    <td style="text-align: center">
                        <input type="checkbox" class="selection" value="<?php echo $article->id; ?>" style="text-align: center">
                    </td>
                    <td><a href="/admin/articles/edit/<?php echo $article->id; ?>"><?php echo $this->htmlEncode($article->headline); ?></a></td>
                    <td><?php echo $this->htmlEncode($this->orm->convertUserIdToName($article->author_id)); ?></td>
                    <td><?php echo $article->start_timestamp->format('Y-m-d H:i'); ?></td>
                    <td>
                        <?php if ($article->publishing_timestamp != null) : ?>
                            <?php echo $this->htmlEncode($article->publishing_timestamp->format('Y-m-d')); ?>
                        <?php endif; ?>
                    </td>
                    <td><?php echo $this->htmlEncode(StatusCode::convertStatusId($article->status_code)); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else : ?>
            <tr>
                <td colspan="6">Keine Artikel gefunden</td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php $this->includeUserTemplate('block-paging.phtml'); ?>