<?php
/* @var $this \Ubergeek\NanoCm\Module\AdminInstallationModule */
?>
<div class="mx-4 my-2">
    <div class="row">
        <div class="info">
            <p>Mit dieser Funktion wird ein neues Backup der aktuellen Installation erstellt.
            Teil des Backups sind auch die Datenbanken, d. h. alle Inhalte und Einstellungen.
                Jedes Backup kann zu einem späteren Zeitpunkt wiederhergestellt werden.</p>
            <p>Das Erstellen eines Backups kann mehrere Minuten in Anspruch nehmen.</p>
            <p class="mb-0">Der Dateiname f&uuml;r ein neues Backup wird automatisch vergeben.</p>
        </div>
        <div class="fs-large text-center mt-4 hidden" id="infoWaiting">
            <span style="vertical-align: middle">Backup wird erstellt</span>
            <img src="ncm/img/blocks-32.gif" width="32" height="32" alt="Bitte warten" title="" style="vertical-align: middle" />
        </div>
    </div>
</div>
