<?php
    /* @var $this \Ubergeek\NanoCm\Module\AdminArticlesModule */
?>
<div class="container">
    <form>
        <h1>Artikel</h1>

        <p>
            <a name="" id="" class="btn btn-primary" href="#" role="button" title="Artikel hinzuf&uuml;gen">+ Neu</a>
            <a name="" id="" class="btn btn-primary" href="#" role="button" title="Ausgew&auml;hlten Artikel bearbeiten">Bearbeiten</a>
            <a name="" id="" class="btn btn-secondary" href="#" role="button" title="Ausgew&auml;hlte Artikel l&ouml;schen">L&ouml;schen</a>
        </p>

        <table class="table table-bordered table-sm">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Titel</th>
                    <th>Autor</th>
                    <th>Pubdate</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <?php if (is_array($this->articles) && count($this->articles) > 0) : ?>
                    <?php foreach ($this->articles as $article) : ?>
                        <tr>
                            <td style="text-align: center">
                                <input type="checkbox" value="<?php echo $article->id; ?>" style="text-align: center">
                            </td>
                            <td><?php echo $this->htmlEncode($article->headline); ?></td>
                            <td><?php echo $this->htmlEncode($this->orm->convertUserIdToName($article->author_id)); ?></td>
                            <td><?php echo $this->htmlEncode($article->publishing_timestamp->format('Y-m-d')); ?></td>
                            <td><?php echo $this->htmlEncode($article->status_code); ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php else : ?>
                    <tr>
                        <td colspan="5">Keine Artikel gefunden</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </form>
</div>
