<?php
/* @var $this \Ubergeek\NanoCm\Module\AdminListsModule */
use Ubergeek\NanoCm\StatusCode;
?>
    <table class="list">
        <thead>
        <tr>
            <th style="text-align: center" width="30"><input type="checkbox" class="selectall" /></th>
            <th>Titel</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        <?php if (is_array($this->lists) && count($this->lists) > 0) : ?>
            <?php foreach ($this->lists as $list) : ?>
                <tr>
                    <td style="text-align: center">
                        <input type="checkbox" class="selection" value="<?php echo $list->id; ?>" style="text-align: center">
                    </td>
                    <td><a href="/admin/lists/listitems/<?php echo intval($list->id); ?>"><?php echo $this->htmlEncode($list->title); ?></a></td>
                    <td><?php echo $this->htmlEncode(StatusCode::convertStatusId($list->status_code)); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php else : ?>
            <tr class="noresult">
                <td colspan="3">Keine Listen gefunden</td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
<?php $this->includeUserTemplate('blocks/list-paging.phtml'); ?>