<?php /* @var $this \Ubergeek\NanoCm\Module\AdminMediaModule */ ?>
<div class="row">
    <div class="info">
        Bitte f&uuml;gen Sie die Youtube-URL f&uuml;r das einzubettende Video ein.<br>
        Die URL sollte folgendes Format besitzen:<br>
            https://www.youtube.com/watch?v=ABCDEFGHIJK
    </div>
</div>
<div class="row">
    <label for="input_media_videolink">Youtube-URL</label>
    <input type="text" id="input_media_videolink" class="autofocus" value="">
</div>
