<?php
    /* @var $this \Ubergeek\NanoCm\Module\AbstractAdminModule */

    $current = $this->getRelativeUrlPart(1);
    $this->log->debug($current);
?>
<nav class="main">
    <a class="logo" href="/admin/index.php">
        <img src="/ncm/img/nanocm-logo.png" alt="NanoCM" title="NanoCM" width="120" />
    </a>

    <ul class="navbar">
        <li class="nav-item<?php if ($current == '' || $current == 'index.php') echo ' active'; ?>">
            <a class="nav-link" href="/admin/index.php">Dashboard</a>
        </li>
        <li class="nav-item<?php if ($current == 'articles') echo ' active'; ?>">
            <a class="nav-link" href="/admin/articles/index.php">Artikel</a>
        </li>
        <li class="nav-item<?php if ($current == 'comments') echo ' active'; ?>">
            <a class="nav-link" href="/admin/comments/index.php">Kommentare</a>
        </li>
        <li class="nav-item<?php if ($current == 'pages') echo ' active'; ?>">
            <a class="nav-link" href="/admin/pages/index.php">Seiten</a>
        </li>
        <li class="nav-item<?php if ($current == 'lists') echo ' active'; ?>">
            <a class="nav-link" href="/admin/lists/index.php">Listen</a>
        </li>
        <li class="nav-item<?php if ($current == 'users') echo ' active'; ?>">
            <a class="nav-link" href="/admin/users/index.php">Benutzer</a>
        </li>
        <li class="nav-item<?php if ($current == 'media') echo ' active'; ?>">
            <a class="nav-link" href="/admin/media/index.php">Medien</a>
        </li>
        <li class="nav-item<?php if ($current == 'stats') echo ' active'; ?>">
            <a class="nav-link" href="/admin/stats/index.php">Statistiken</a>
        </li>
        <li class="nav-item<?php if ($current == 'settings') echo ' active'; ?>">
            <a class="nav-link" href="/admin/settings/index.php">Einstellungen</a>
        </li>
        <li class="nav-item"><a href="/logout.php" class="nav-link">Logout</a></li>
    </ul>
</nav>
