<!DOCTYPE html>
<?php /* @var $this \Ubergeek\NanoCm\Module\AbstractAdminModule */ ?>
<html lang="de">
    <head>
        <meta charset="utf-8">        
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <base href="<?php echo $this->getBaseUrl(); ?>">
        <link rel="stylesheet" href="/ncm/css/admin.css">
        <title><?php echo $this->htmlEncode($this->getTitle()); ?></title>
        <script src="/ncm/js/jquery-3.3.1.min.js"></script>
        <script src="/ncm/js/ncm-admin.js" type="text/javascript"></script>
    </head>
    <body>
        <div class="blanker" id="globalblanker"></div>
        <?php echo $this->includeUserTemplate('navigation-main.phtml'); ?>
        <?php echo $this->getContent(); ?>
        <div class="container spacing">
            <footer>
                <p>NanoCM &copy; 2017, 2018 Andr&eacute; Gewert
                    <?php if ($this->ncm->isUserLoggedIn()) : ?>
                        &middot; <a href="/logout.php">Abmelden</a>
                    <?php endif; ?> &middot;
                    <a href="http://www.ubergeek.de/">www.ubergeek.de</a>
                </p>
            </footer>
        </div>
    </body>
</html>