<!DOCTYPE html>
<?php
    /* @var $this \Ubergeek\NanoCm\Module\SetupModule */
?>
<html lang="de">
    <head>
        <meta charset="utf-8">        
        <title>nanoCM: Ersteinrichtung</title>
        <link rel="stylesheet" href="ncm/css/setup.css">
        <script src="<?php echo $this->htmlConvUrl('/ncm/js/jquery-3.3.1.min.js'); ?>"></script>
        <script src="<?php echo $this->htmlConvUrl('/ncm/js/ncm-setup.js'); ?>" type="text/javascript"></script>
    </head>
    <body>
        <main role="main" class="container">
            <?php echo $this->getContent(); ?>
        </main>
        <footer>
            <p>NanoCM &copy; 2017&nbsp;&ndash; 2020 Andr&eacute; Gewert
                <?php if ($this->ncm->isUserLoggedIn()) : ?>
                    &middot; <a href="<?php echo $this->htmlConvUrl('/logout.php'); ?>">Abmelden</a>
                <?php endif; ?> &middot;
                <a href="http://www.ubergeek.de/">www.ubergeek.de</a>
            </p>
        </footer>
    </body>
</html>