<!DOCTYPE html>
<?php /* @var $this \Ubergeek\NanoCm\Module\AbstractAdminModule */ ?>
<html lang="de">
    <head>
        <meta charset="utf-8">        
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <base href="<?php echo $this->getBaseUrl(); ?>">
        <link rel="stylesheet" href="/ncm/css/default.css">
        <title><?php echo $this->htmlEncode($this->getTitle()); ?></title>
    </head>
    <body>
        <?php echo $this->includeUserTemplate('navigation-main.phtml'); ?>
        
        <?php echo $this->getContent(); ?>
        
        <div class="container">
            <hr>
            <footer>
                <p>NanoCM &copy; 2017 Andr&eacute; Gewert
                    <?php if ($this->ncm->isUserLoggedIn()) : ?>
                        &middot; <a href="/logout.php">Abmelden</a>
                    <?php endif; ?> &middot;
                    <a href="http://www.ubergeek.de/">www.ubergeek.de</a>
                </p>
            </footer>
        </div>
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    </body>
</html>