<?php
    /* @var $this \Ubergeek\NanoCm\Module\AbstractAdminModule */
    $vars = json_decode($this->getParam('vars'), true);
    if (!is_array($vars)) $vars = array();
?>
<table class="list" id="editvars_list">
    <tr>
        <th>Variable</th>
        <th>Wert</th>
        <th></th>
    </tr>
    <?php foreach ($vars as $key => $value) : ?>
        <tr class="entry">
            <td>
                <input style="width: 100%" type="text" class="key" value="<?php echo $this->htmlEncode($key); ?>">
            </td>
            <td>
                <input style="width: 100%" type="text" class="value" value="<?php echo $this->htmlEncode($value); ?>">
            </td>
            <td style="text-align: center">
                <a href="javascript:void(0);" onclick="editVars.removeRow(this)"><img src="ncm/img/fatcow/16/delete.png" width="16" height="16" style="vertical-align: middle"></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<div style="text-align: right">
    <a href="javascript:void(0);" onclick="editVars.addRow();">
        <img src="ncm/img/fatcow/16/add.png" width="16" height="16" style="vertical-align: middle">Hinzuf&uuml;gen
    </a>
</div>

<script type="text/javascript">
    var editVars;
    if (typeof editVars == 'undefined') {
        editVars = new (function () {
            let app = this;

            app.removeRow = function (clickedElem) {
                let tr = $(clickedElem).parents('tr');
                $(tr).remove();
            };

            app.getValue = function () {
                let vars = {};
                $('#editvars_list').find('tr.entry').each(function () {
                    var key = $(this).find('input.key').val();
                    var value = $(this).find('input.value').val();
                    if (key.length > 0) {
                        vars[key] = value;
                    }
                });
                let val = JSON.stringify(vars);
                if (val == '{}') val = '';
                return val;
            };

            app.addRow = function () {
                let table = $('#editvars_list').get(0);

                var row = document.createElement('tr');
                row.setAttribute('class', 'entry');
                var td, input;
                var image, link;

                td = document.createElement('td');
                input = document.createElement('input');
                input.setAttribute('type', 'text');
                input.setAttribute('class', 'key');
                input.setAttribute('style', 'width: 100%');
                td.appendChild(input);
                row.appendChild(td);

                td = document.createElement('td');
                input = document.createElement('input');
                input.setAttribute('type', 'text');
                input.setAttribute('class', 'value');
                input.setAttribute('style', 'width: 100%');
                td.appendChild(input);
                row.appendChild(td);

                td = document.createElement('td');
                td.setAttribute('style', 'text-align: center');
                link = document.createElement('a');
                link.setAttribute('href', 'javascript:void(0);');
                link.setAttribute('onclick', 'editVars.removeRow(this)');
                image = document.createElement('img');
                image.setAttribute('src', 'ncm/img/fatcow/16/delete.png');
                image.setAttribute('width', '16');
                image.setAttribute('height', '16');
                image.setAttribute('style', 'vertical-align: middle');
                link.appendChild(image);
                td.appendChild(link);
                row.appendChild(td);

                table.appendChild(row);

                app.getValue();
            };
        })();
    }
</script>